In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

# D√°n ƒë∆∞·ªùng d·∫´n c·ªßa file v√†o ƒë√¢y
file_path = '/content/drive/MyDrive/AIO/top 30 main categories.csv'
# Thay '/content/drive/MyDrive/...' b·∫±ng ƒë∆∞·ªùng d·∫´n th·∫≠t c·ªßa b·∫°n

df = pd.read_csv(file_path)

# In 5 d√≤ng ƒë·∫ßu ti√™n c·ªßa file ƒë·ªÉ ki·ªÉm tra
print(df.head())

                                             authors  \
0       Yongli Ping, Lixin Xu, Hongya Liu, Ying Shao   
1  David Keitel, Rodrigo Tenorio, Gregory Ashton,...   
2             Jiliang Jing, Qiyuan Pan, Songbai Chen   
3  R. Hole\v{n}\'ak, S. Lohmann, F. Sekula and D....   
4                Szabolcs Horv\'at and Carl D. Modes   

                                               title  \
0  Power-law cosmological solution derived from D...   
1  PyFstat: a Python package for continuous gravi...   
2  Holographic Superconductors with Power-Maxwell...   
3  Simultaneous assessment of energy, charge stat...   
4  Connectedness matters: Construction and exact ...   

                                            abstract  \
0    By studying a tachyon field on the DGP brane...   
1    Gravitational waves in the sensitivity band ...   
2    With the Sturm-Liouville analytical and nume...   
3    We demonstrate simultaneous measurements of ...   
4    We describe a new method for the random s

In [ ]:
# Gi·∫£ s·ª≠ DataFrame c·ªßa b·∫°n ƒë√£ ƒë∆∞·ª£c ƒë·ªçc v√†o bi·∫øn df
# Code ƒë·ªÉ ƒë·ªïi t√™n c√°c c·ªôt
df = df.rename(columns={
    'categories': 'child_labels',
    'main_categories': 'parent_labels'
})

# In ra 5 d√≤ng ƒë·∫ßu ti√™n c·ªßa DataFrame ƒë√£ ƒë∆∞·ª£c ƒë·ªïi t√™n ƒë·ªÉ ki·ªÉm tra
print(df.head())

                                             authors  \
0       Yongli Ping, Lixin Xu, Hongya Liu, Ying Shao   
1  David Keitel, Rodrigo Tenorio, Gregory Ashton,...   
2             Jiliang Jing, Qiyuan Pan, Songbai Chen   
3  R. Hole\v{n}\'ak, S. Lohmann, F. Sekula and D....   
4                Szabolcs Horv\'at and Carl D. Modes   

                                               title  \
0  Power-law cosmological solution derived from D...   
1  PyFstat: a Python package for continuous gravi...   
2  Holographic Superconductors with Power-Maxwell...   
3  Simultaneous assessment of energy, charge stat...   
4  Connectedness matters: Construction and exact ...   

                                            abstract  \
0    By studying a tachyon field on the DGP brane...   
1    Gravitational waves in the sensitivity band ...   
2    With the Sturm-Liouville analytical and nume...   
3    We demonstrate simultaneous measurements of ...   
4    We describe a new method for the random s

In [ ]:
df = df[['abstract', 'parent_labels', 'child_labels']]

In [ ]:
df['parent_labels'].value_counts()

parent_labels
['hep-th']                  2000
['gr-qc', 'astro-ph']       2000
['hep-th', 'gr-qc']         2000
['physics']                 2000
['quant-ph', 'physics']     2000
['quant-ph']                2000
['quant-ph', 'cond-mat']    2000
['hep-ph', 'nucl-th']       2000
['gr-qc']                   2000
['cond-mat']                2000
['q-bio']                   2000
['gr-qc', 'hep-th']         2000
['nucl-th']                 2000
['hep-ex']                  2000
['hep-ph', 'astro-ph']      2000
['hep-ph', 'hep-ex']        2000
['hep-lat']                 2000
['nlin']                    2000
['econ']                    2000
['eess']                    2000
['cs']                      2000
['math-ph', 'math']         2000
['nucl-ex']                 2000
['hep-th', 'cond-mat']      2000
['hep-ph']                  2000
['math']                    2000
['stat']                    2000
['astro-ph']                2000
['hep-ph', 'hep-th']        2000
['q-fin']                   2000
Name: count, dtype: int64

In [ ]:
df.shape

(60000, 3)

In [ ]:
df.head(3)

abstract          parent_labels  \
0    By studying a tachyon field on the DGP brane...             ['hep-th']   
1    Gravitational waves in the sensitivity band ...  ['gr-qc', 'astro-ph']   
2    With the Sturm-Liouville analytical and nume...    ['hep-th', 'gr-qc']   

        child_labels  
0             hep-th  
1  gr-qc astro-ph.IM  
2       hep-th gr-qc

In [ ]:
type(df['parent_labels'])

pandas.core.series.Series

In [ ]:
df['parent_labels'].head(3)

0               ['hep-th']
1    ['gr-qc', 'astro-ph']
2      ['hep-th', 'gr-qc']
Name: parent_labels, dtype: object

### tai model va luu vao drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from sentence_transformers import SentenceTransformer
import os

# ƒê·ªãnh nghƒ©a ƒë∆∞·ªùng d·∫´n t·ªõi th∆∞ m·ª•c ƒë√£ l∆∞u m√¥ h√¨nh tr√™n Drive
# Ch√∫ √Ω: ƒê√¢y ph·∫£i l√† ƒë∆∞·ªùng d·∫´n ch√≠nh x√°c n∆°i b·∫°n ƒë√£ l∆∞u m√¥ h√¨nh
model_load_path = '/content/drive/My Drive/Colab_Models/MiniLM-L6-v2'

# Ki·ªÉm tra xem ƒë∆∞·ªùng d·∫´n c√≥ t·ªìn t·∫°i kh√¥ng
if not os.path.exists(model_load_path):
    raise FileNotFoundError(f"L·ªói: Kh√¥ng t√¨m th·∫•y m√¥ h√¨nh t·∫°i ƒë∆∞·ªùng d·∫´n '{model_load_path}'. Vui l√≤ng ki·ªÉm tra l·∫°i.")

print(f"ƒêang t·∫£i m√¥ h√¨nh t·ª´: {model_load_path}")
try:
    # T·∫£i m√¥ h√¨nh t·ª´ ƒë∆∞·ªùng d·∫´n ƒë√£ l∆∞u tr√™n Drive
    model = SentenceTransformer(model_load_path)
    print("ƒê√£ t·∫£i m√¥ h√¨nh th√†nh c√¥ng!")

except Exception as e:
    print(f"L·ªói: C√≥ v·∫•n ƒë·ªÅ khi t·∫£i m√¥ h√¨nh.")
    print(f"Th√¥ng tin chi ti·∫øt: {e}")

###embedding vƒÉn b·∫£n th√¥i

In [ ]:
import pickle
import numpy as np

In [ ]:
# T·∫°o embeddings cho c·ªôt 'abstract'
print("\nƒêang t·∫°o embeddings cho c·ªôt 'abstract'...")
abstract_embeddings = model.encode(df['abstract'].tolist(), show_progress_bar=True)
print("ƒê√£ t·∫°o xong embeddings cho c·ªôt 'abstract'.")
print(f"K√≠ch th∆∞·ªõc c·ªßa abstract embeddings: {abstract_embeddings.shape}")


ƒêang t·∫°o embeddings cho c·ªôt 'abstract'...


Batches:   0%|          | 0/938 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [ ]:
# S·ª≠ d·ª•ng 4 l√µi CPU ƒë·ªÉ x·ª≠ l√Ω song song
num_workers = 4
abstract_embeddings = model.encode(
    df['abstract'].tolist(),
    show_progress_bar=True,
    num_workers=num_workers,
    convert_to_tensor=True
)

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [ ]:
import torch

if torch.cuda.is_available():
    print("GPU c√≥ s·∫µn v√† ƒëang ƒë∆∞·ª£c s·ª≠ d·ª•ng.")
    print(f"T√™n GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU kh√¥ng c√≥ s·∫µn. ƒêang s·ª≠ d·ª•ng CPU.")

GPU c√≥ s·∫µn v√† ƒëang ƒë∆∞·ª£c s·ª≠ d·ª•ng.
T√™n GPU: Tesla T4


In [ ]:
import pandas as pd
import torch
from sentence_transformers import SentenceTransformer
# 1. Ki·ªÉm tra v√† s·ª≠ d·ª•ng GPU n·∫øu c√≥
device = 'cuda' if torch.cuda.is_available() else 'cpu'
if device == 'cuda':
    print("üöÄ GPU (CUDA) ƒë√£ s·∫µn s√†ng. TƒÉng t·ªëc ƒë·ªô t√≠nh to√°n!")
else:
    print("üòî GPU kh√¥ng kh·∫£ d·ª•ng. ƒêang ch·∫°y tr√™n CPU.")

# 2. T·∫£i m√¥ h√¨nh v√† chuy·ªÉn n√≥ sang GPU
# 'all-MiniLM-L6-v2' l√† m·ªôt trong nh·ªØng m√¥ h√¨nh nhanh v√† hi·ªáu qu·∫£ nh·∫•t
model = SentenceTransformer('all-MiniLM-L6-v2', device=device)

# 3. T·∫°o embeddings v·ªõi t·ªëi ∆∞u h√≥a
# Tham s·ªë num_workers gi√∫p tƒÉng t·ªëc ƒë·ªô n·∫°p d·ªØ li·ªáu v√†o GPU, tr√°nh "n√∫t c·ªï chai" CPU
print("\nƒêang t·∫°o embeddings cho c·ªôt 'abstract'...")
abstract_embeddings = model.encode(
    df['abstract'].tolist(),
    show_progress_bar=True,
    num_workers=2, # S·ª≠ d·ª•ng 2 lu·ªìng CPU ƒë·ªÉ ti·ªÅn x·ª≠ l√Ω d·ªØ li·ªáu
    batch_size=256, # K√≠ch th∆∞·ªõc batch l·ªõn gi√∫p GPU ho·∫°t ƒë·ªông hi·ªáu qu·∫£ h∆°n
    normalize_embeddings=True # Th√™m tham s·ªë n√†y ƒë·ªÉ chu·∫©n h√≥a t·ª± ƒë·ªông
    )
print("ƒê√£ t·∫°o xong embeddings cho c·ªôt 'abstract'.")
print(f"K√≠ch th∆∞·ªõc c·ªßa abstract embeddings: {abstract_embeddings.shape}")

üöÄ GPU (CUDA) ƒë√£ s·∫µn s√†ng. TƒÉng t·ªëc ƒë·ªô t√≠nh to√°n!


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]


ƒêang t·∫°o embeddings cho c·ªôt 'abstract'...


Batches:   0%|          | 0/235 [00:00<?, ?it/s]

ƒê√£ t·∫°o xong embeddings cho c·ªôt 'abstract'.
K√≠ch th∆∞·ªõc c·ªßa abstract embeddings: (60000, 384)


In [ ]:
abstract_embeddings.shape

(60000, 384)

embedding unique label nh√£n cha l∆∞u th√†nh

In [ ]:
import ast
import pandas as pd # Gi·∫£ s·ª≠ b·∫°n ƒëang d√πng pandas

# H√†m ƒë·ªÉ chuy·ªÉn ƒë·ªïi an to√†n, ch·ªâ √°p d·ª•ng literal_eval n·∫øu l√† chu·ªói
def safe_literal_eval(data):
    if isinstance(data, str):
        try:
            return ast.literal_eval(data)
        except (ValueError, SyntaxError):
            # Tr·∫£ v·ªÅ m·ªôt danh s√°ch r·ªóng ho·∫∑c x·ª≠ l√Ω l·ªói n·∫øu chu·ªói kh√¥ng h·ª£p l·ªá
            return []
    # N·∫øu ƒë√£ l√† list ho·∫∑c ki·ªÉu d·ªØ li·ªáu kh√°c, tr·∫£ v·ªÅ nguy√™n b·∫£n
    return data

# B∆Ø·ªöC M·ªöI V√Ä QUAN TR·ªåNG: √Åp d·ª•ng h√†m chuy·ªÉn ƒë·ªïi an to√†n
df['parent_labels'] = df['parent_labels'].apply(safe_literal_eval)

# 3. San ph·∫≥ng (flatten) d·ªØ li·ªáu v√† l·∫•y c√°c nh√£n duy nh·∫•t
all_parent_labels_flat = [label for sublist in df['parent_labels'] for label in sublist if label and label.isalnum()]
unique_parent_labels = sorted(list(set(all_parent_labels_flat)))

print("\nƒê√£ l·∫•y xong c√°c nh√£n 'parent_labels' duy nh·∫•t.")
print(f"Danh s√°ch c√°c nh√£n duy nh·∫•t: {unique_parent_labels}")

# 4. T·∫°o embeddings cho c√°c nh√£n v√† chu·∫©n h√≥a
print("\nƒêang t·∫°o embeddings cho c√°c 'parent_labels' v√† chu·∫©n h√≥a...")
parent_label_embeddings_list = model.encode(
    unique_parent_labels,
    show_progress_bar=True,
    normalize_embeddings=True # Th√™m tham s·ªë n√†y ƒë·ªÉ chu·∫©n h√≥a vector
)
print("ƒê√£ t·∫°o xong v√† chu·∫©n h√≥a embeddings.")

# 5. T·∫°o dictionary √°nh x·∫° nh√£n v·ªõi embeddings ƒë√£ chu·∫©n h√≥a
parent_label_dict = {name: embedding for name, embedding in zip(unique_parent_labels, parent_label_embeddings_list)}
print("\nƒê√£ t·∫°o xong dictionary cho parent_labels.")
print(f"S·ªë l∆∞·ª£ng entries trong dictionary: {len(parent_label_dict)}")


ƒê√£ l·∫•y xong c√°c nh√£n 'parent_labels' duy nh·∫•t.
Danh s√°ch c√°c nh√£n duy nh·∫•t: ['cs', 'econ', 'eess', 'math', 'nlin', 'physics', 'stat']

ƒêang t·∫°o embeddings cho c√°c 'parent_labels' v√† chu·∫©n h√≥a...


NameError: name 'model' is not defined

In [ ]:
type(parent_label_dict)

dict

In [ ]:
# In ra t·ªïng s·ªë items
so_luong_item = len(parent_label_dict)
print(f"T·ªïng s·ªë item trong dict: {so_luong_item}")

T·ªïng s·ªë item trong dict: 7


In [ ]:
counter = 0
for key, value in parent_label_dict.items():
    if counter < 20:
        print(f"Key: {key} -> Value: {value.shape}")
        counter += 1
    else:
        break # D·ª´ng v√≤ng l·∫∑p sau khi ƒë√£ in ƒë·ªß 5 item

Key: cs -> Value: (384,)
Key: econ -> Value: (384,)
Key: eess -> Value: (384,)
Key: math -> Value: (384,)
Key: nlin -> Value: (384,)
Key: physics -> Value: (384,)
Key: stat -> Value: (384,)


In [ ]:
parent_label_dict.items()

dict_items([('cs', array([-6.09161854e-02,  4.02116217e-02, -9.09962207e-02,  7.09643587e-02,
       -4.79100039e-03, -6.24113493e-02,  9.76989120e-02,  2.21683607e-02,
        1.96847115e-02,  4.15325351e-03, -4.99133207e-02, -8.47239122e-02,
        4.57276665e-02, -4.64608409e-02, -2.60798857e-02, -2.12841271e-03,
        2.10789796e-02, -4.10184637e-02, -6.56680167e-02, -4.45803292e-02,
       -1.33160159e-01, -8.48432407e-02, -4.96465974e-02,  6.83533261e-03,
       -2.70084161e-02,  4.89896089e-02, -1.69768091e-02,  3.46207470e-02,
        2.91205361e-03, -1.05241172e-01, -6.99328855e-02,  9.88640357e-03,
        1.06534071e-01,  2.47874148e-02, -5.16984612e-02, -3.65980677e-02,
        1.19524542e-02, -2.19083428e-02, -9.03326422e-02,  1.04752863e-02,
       -4.12750989e-02, -8.27054027e-03,  2.44851969e-02,  2.30973568e-02,
        4.61381637e-02, -2.73780245e-03, -1.56594254e-02, -1.44659886e-02,
       -2.54759695e-02,  8.93610120e-02, -6.37395382e-02, -4.27874550e-02,
      

### l∆∞u l·∫°i ket qua

# 1.T·∫£i .pkl ƒë√£ x·ª≠ l√Ω t·ª´ Google Drive

Ph·∫ßn code n√†y th·ª±c hi·ªán vi·ªác t·∫£i c√°c d·ªØ li·ªáu ƒë√£ ƒë∆∞·ª£c x·ª≠ l√Ω v√† l∆∞u tr∆∞·ªõc ƒë√≥ d∆∞·ªõi d·∫°ng file `.pkl` tr√™n Google Drive. ƒêi·ªÅu n√†y gi√∫p b·∫°n ti·∫øp t·ª•c c√¥ng vi·ªác m√† kh√¥ng c·∫ßn ch·∫°y l·∫°i c√°c b∆∞·ªõc ti·ªÅn x·ª≠ l√Ω v√† t·∫°o embeddings t·ª´ ƒë·∫ßu.

1.  **Mount Google Drive:**
    *   Ki·ªÉm tra v√† mount (g·∫Øn k·∫øt) Google Drive v√†o m√¥i tr∆∞·ªùng Colab ƒë·ªÉ c√≥ th·ªÉ truy c·∫≠p c√°c file ƒë√£ l∆∞u. N·∫øu Drive ƒë√£ ƒë∆∞·ª£c mount, th√¥ng b√°o s·∫Ω hi·ªÉn th·ªã.

2.  **Ch·ªâ ƒë·ªãnh ƒë∆∞·ªùng d·∫´n file:**
    *   Bi·∫øn `file_path` ch·ª©a ƒë∆∞·ªùng d·∫´n c·ª• th·ªÉ ƒë·∫øn file `30Kdata.pkl` tr√™n Google Drive c·ªßa b·∫°n. ƒê·∫£m b·∫£o ƒë∆∞·ªùng d·∫´n n√†y l√† ch√≠nh x√°c.

3.  **T·∫£i d·ªØ li·ªáu t·ª´ file `.pkl`:**
    *   S·ª≠ d·ª•ng th∆∞ vi·ªán `pickle` ƒë·ªÉ m·ªü v√† ƒë·ªçc file nh·ªã ph√¢n (`'rb'`).
    *   H√†m `pickle.load(f)` s·∫Ω deserialze (gi·∫£i m√£) d·ªØ li·ªáu t·ª´ file v√† t·∫£i n√≥ v√†o dictionary `loaded_data`.

4.  **G√°n d·ªØ li·ªáu v√†o c√°c bi·∫øn:**
    *   C√°c tr∆∞·ªùng ('abstract_embeddings', 'parent_label_embeddings_dict', 'original_abstracts', 'original_parent_labels', 'original_children_labels') t·ª´ dictionary `loaded_data` ƒë∆∞·ª£c g√°n v√†o c√°c bi·∫øn ri√™ng bi·ªát ƒë·ªÉ d·ªÖ d√†ng s·ª≠ d·ª•ng trong c√°c b∆∞·ªõc ti·∫øp theo.

5.  **Ki·ªÉm tra v√† b√°o c√°o:**
    *   In ra th√¥ng b√°o x√°c nh·∫≠n vi·ªác t·∫£i file th√†nh c√¥ng v√† li·ªát k√™ c√°c bi·∫øn ƒë√£ ƒë∆∞·ª£c t·∫£i.
    *   X·ª≠ l√Ω tr∆∞·ªùng h·ª£p kh√¥ng t√¨m th·∫•y file (`FileNotFoundError`) ho·∫∑c c√°c l·ªói kh√°c trong qu√° tr√¨nh t·∫£i.

### T√°i t·∫°o Dictionary `processed_data`

Sau khi t·∫£i c√°c bi·∫øn d·ªØ li·ªáu ri√™ng l·∫ª, ƒëo·∫°n code n√†y t·∫≠p h·ª£p l·∫°i ch√∫ng v√†o m·ªôt dictionary duy nh·∫•t c√≥ t√™n `processed_data`. C·∫•u tr√∫c n√†y gi·ªëng v·ªõi dictionary ƒë√£ ƒë∆∞·ª£c l∆∞u ban ƒë·∫ßu, gi√∫p gi·ªØ t√≠nh nh·∫•t qu√°n v√† d·ªÖ d√†ng truy c·∫≠p d·ªØ li·ªáu theo c√πng m·ªôt c√°ch.

1.  **T·∫°o Dictionary m·ªõi:**
    *   M·ªôt dictionary m·ªõi ƒë∆∞·ª£c t·∫°o ra v·ªõi c√°c key t∆∞∆°ng ·ª©ng ('abstract_embeddings', 'parent_label_embeddings_dict', 'original_abstracts', 'original_parent_labels', 'original_children_labels').
    *   C√°c bi·∫øn ƒë√£ t·∫£i ·ªü b∆∞·ªõc tr∆∞·ªõc ƒë∆∞·ª£c g√°n l√†m value cho c√°c key n√†y.

2.  **Ki·ªÉm tra Dictionary ƒë√£ t√°i t·∫°o:**
    *   In ra th√¥ng b√°o x√°c nh·∫≠n dictionary `processed_data` ƒë√£ ƒë∆∞·ª£c t·∫°o l·∫°i th√†nh c√¥ng v√† li·ªát k√™ c√°c key c√≥ trong ƒë√≥.

C√°c b∆∞·ªõc n√†y ƒë·∫£m b·∫£o r·∫±ng t·∫•t c·∫£ d·ªØ li·ªáu c·∫ßn thi·∫øt ƒë√£ s·∫µn s√†ng trong m√¥i tr∆∞·ªùng l√†m vi·ªác ƒë·ªÉ ti·∫øp t·ª•c c√°c ph√¢n t√≠ch ho·∫∑c x√¢y d·ª±ng m√¥ h√¨nh, v√≠ d·ª• nh∆∞ s·ª≠ d·ª•ng cho Nearest Neighbor Search (ANN) ho·∫∑c c√°c thu·∫≠t to√°n h·ªçc m√°y kh√°c.

In [1]:
import pickle
from google.colab import drive

# Mount Google Drive if not already mounted
try:
    drive.mount('/content/drive')
except:
    print("Drive already mounted.")

# Define the path to the pickle file
file_path = '/content/drive/MyDrive/AIO/30Kdata.pkl'

# Load the data from the pickle file
try:
    with open(file_path, 'rb') as f:
        loaded_data = pickle.load(f)

    # Assign the loaded data to the respective variables
    abstract_embeddings = loaded_data['abstract_embeddings']
    parent_label_embeddings_dict = loaded_data['parent_label_embeddings_dict']
    original_abstracts = loaded_data['original_abstracts']
    original_parent_labels = loaded_data['original_parent_labels']
    original_children_labels = loaded_data['original_children_labels']

    print(f"Successfully loaded data from: {file_path}")
    print(f"Loaded variables: {list(loaded_data.keys())}")

except FileNotFoundError:
    print(f"Error: File not found at {file_path}. Please check the path.")
except Exception as e:
    print(f"Error loading data: {e}")

Mounted at /content/drive
Successfully loaded data from: /content/drive/MyDrive/AIO/30Kdata.pkl
Loaded variables: ['abstract_embeddings', 'parent_label_embeddings_dict', 'original_abstracts', 'original_parent_labels', 'original_children_labels']


In [2]:
# Recreate the processed_data dictionary from the loaded variables
processed_data = {
    'abstract_embeddings': abstract_embeddings,
    'parent_label_embeddings_dict': parent_label_embeddings_dict,
    'original_abstracts': original_abstracts,
    'original_parent_labels': original_parent_labels,
    'original_children_labels': original_children_labels
}

print("\nƒê√£ t√°i t·∫°o dictionary processed_data.")
print(f"C√°c tr∆∞·ªùng trong processed_data: {list(processed_data.keys())}")


ƒê√£ t√°i t·∫°o dictionary processed_data.
C√°c tr∆∞·ªùng trong processed_data: ['abstract_embeddings', 'parent_label_embeddings_dict', 'original_abstracts', 'original_parent_labels', 'original_children_labels']


## 1.1 Ki·ªÉm tra file.pkl

In [3]:
type(processed_data)

dict

In [4]:
# In d·ªØ li·ªáu c·ªßa 25 m·∫´u ƒë·∫ßu ti√™n t·ª´ processed_data
num_samples_to_show = 25

print(f"--- Hi·ªÉn th·ªã d·ªØ li·ªáu c·ªßa {num_samples_to_show} m·∫´u ƒë·∫ßu ti√™n t·ª´ 'processed_data' ---")

# Ki·ªÉm tra xem processed_data c√≥ c√°c key c·∫ßn thi·∫øt kh√¥ng
if all(key in processed_data for key in ['original_abstracts', 'original_parent_labels', 'original_children_labels']):
    for i in range(num_samples_to_show):
        if i < len(processed_data['original_abstracts']): # ƒê·∫£m b·∫£o kh√¥ng v∆∞·ª£t qu√° s·ªë l∆∞·ª£ng m·∫´u th·ª±c t·∫ø
            print(f"\n--- M·∫´u {i+1} ---")
            # Hi·ªÉn th·ªã m·ªôt ph·∫ßn abstract ƒë·ªÉ ng·∫Øn g·ªçn
            print(f"Abstract: {processed_data['original_abstracts'][i][:200]}...")
            print(f"Nh√£n Cha: {processed_data['original_parent_labels'][i]}")
            print(f"Nh√£n Con: {processed_data['original_children_labels'][i]}")
            print("-" * 30)
        else:
            print(f"\nƒê√£ h·∫øt m·∫´u sau {i} m·∫´u.")
            break
else:
    print("\nL·ªói: Dictionary 'processed_data' kh√¥ng ch·ª©a c√°c tr∆∞·ªùng c·∫ßn thi·∫øt (original_abstracts, original_parent_labels, original_children_labels).")
    print(f"C√°c tr∆∞·ªùng hi·ªán c√≥: {list(processed_data.keys())}")

--- Hi·ªÉn th·ªã d·ªØ li·ªáu c·ªßa 25 m·∫´u ƒë·∫ßu ti√™n t·ª´ 'processed_data' ---

--- M·∫´u 1 ---
Abstract:   By studying a tachyon field on the DGP brane model, in order to embed the 4D
standard Friedmann equation with a brane tachyon field in 5D bulk, the metric
of the 5D spacetime is presented. Then, ado...
Nh√£n Cha: ['hep-th']
Nh√£n Con: hep-th
------------------------------

--- M·∫´u 2 ---
Abstract:   Gravitational waves in the sensitivity band of ground-based detectors can be
emitted by a number of astrophysical sources, including not only binary
coalescences, but also individual spinning neutro...
Nh√£n Cha: ['gr-qc', 'astro-ph']
Nh√£n Con: gr-qc astro-ph.IM
------------------------------

--- M·∫´u 3 ---
Abstract:   With the Sturm-Liouville analytical and numerical methods, we investigate the
behaviors of the holographic superconductors by introducing a complex charged
scalar field coupled with a Power-Maxwell ...
Nh√£n Cha: ['hep-th', 'gr-qc']
Nh√£n Con: hep-th gr-qc
-----

In [5]:
# Kh√°m ph√° c·∫•u tr√∫c c·ªßa dictionary processed_data
print("--- Kh√°m ph√° dictionary 'processed_data' ---")
print(f"S·ªë l∆∞·ª£ng c·∫∑p key-value trong dictionary: {len(processed_data)}")

print("\n--- Th√¥ng tin chi ti·∫øt v·ªÅ t·ª´ng tr∆∞·ªùng trong dictionary ---")
for key, value in processed_data.items():
    print(f"Key: {key}")
    # Ki·ªÉm tra xem c√≥ ph·∫£i l√† NumPy array ho·∫∑c ƒë·ªëi t∆∞·ª£ng t∆∞∆°ng t·ª± kh√¥ng
    if hasattr(value, 'shape'):
        print(f"  - Ki·ªÉu d·ªØ li·ªáu: {type(value)}")
        print(f"  - K√≠ch th∆∞·ªõc (shape): {value.shape}")
    # N·∫øu l√† list ho·∫∑c dict, in ra ƒë·ªô d√†i c·ªßa ch√∫ng
    elif isinstance(value, (list, dict)):
        print(f"  - Ki·ªÉu d·ªØ li·ªáu: {type(value)}")
        print(f"  - S·ªë l∆∞·ª£ng ph·∫ßn t·ª≠ (len): {len(value)}")
    # Cho c√°c tr∆∞·ªùng h·ª£p kh√°c
    else:
        print(f"  - Ki·ªÉu d·ªØ li·ªáu: {type(value)}")
        # Tr√°nh in gi√° tr·ªã l·ªõn, ch·ªâ in ƒë·∫°i di·ªán n·∫øu c·∫ßn
        # print(f"  - Gi√° tr·ªã (v√≠ d·ª•): {str(value)[:100]}...")

    print("-" * 20) # Th√™m d√≤ng ph√¢n c√°ch

--- Kh√°m ph√° dictionary 'processed_data' ---
S·ªë l∆∞·ª£ng c·∫∑p key-value trong dictionary: 5

--- Th√¥ng tin chi ti·∫øt v·ªÅ t·ª´ng tr∆∞·ªùng trong dictionary ---
Key: abstract_embeddings
  - Ki·ªÉu d·ªØ li·ªáu: <class 'numpy.ndarray'>
  - K√≠ch th∆∞·ªõc (shape): (60000, 384)
--------------------
Key: parent_label_embeddings_dict
  - Ki·ªÉu d·ªØ li·ªáu: <class 'dict'>
  - S·ªë l∆∞·ª£ng ph·∫ßn t·ª≠ (len): 7
--------------------
Key: original_abstracts
  - Ki·ªÉu d·ªØ li·ªáu: <class 'list'>
  - S·ªë l∆∞·ª£ng ph·∫ßn t·ª≠ (len): 60000
--------------------
Key: original_parent_labels
  - Ki·ªÉu d·ªØ li·ªáu: <class 'list'>
  - S·ªë l∆∞·ª£ng ph·∫ßn t·ª≠ (len): 60000
--------------------
Key: original_children_labels
  - Ki·ªÉu d·ªØ li·ªáu: <class 'list'>
  - S·ªë l∆∞·ª£ng ph·∫ßn t·ª≠ (len): 60000
--------------------


# 1. Ti·ªÅn x·ª≠ l√Ω d·ªØ li·ªáu ban ƒë·∫ßu v·ªÅ d·∫°ng json cha con

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import pandas as pd

# D√°n ƒë∆∞·ªùng d·∫´n c·ªßa file v√†o ƒë√¢y
file_path = '/content/drive/MyDrive/AIO/top 30 main categories.csv'
# Thay '/content/drive/MyDrive/...' b·∫±ng ƒë∆∞·ªùng d·∫´n th·∫≠t c·ªßa b·∫°n

df = pd.read_csv(file_path)

# In 5 d√≤ng ƒë·∫ßu ti√™n c·ªßa file ƒë·ªÉ ki·ªÉm tra
df.head(25)

authors  \
0        Yongli Ping, Lixin Xu, Hongya Liu, Ying Shao   
1   David Keitel, Rodrigo Tenorio, Gregory Ashton,...   
2              Jiliang Jing, Qiyuan Pan, Songbai Chen   
3   R. Hole\v{n}\'ak, S. Lohmann, F. Sekula and D....   
4                 Szabolcs Horv\'at and Carl D. Modes   
5                          A. Hopper and P. F. Barker   
6                   Zeyang Liao and M. Suhail Zubairy   
7   Christian Majenz, Maris Ozols, Christian Schaf...   
8   Sergey Khaykin, Bernard Legras, Silvia Bucci, ...   
9                    Wenchao Ge and M. Suhail Zubairy   
10              Grzegorz Wilk and Zbigniew Wlodarczyk   
11                 Alexander Grant, Eanna E. Flanagan   
12                                      M. A. Sol\'is   
13                                   Kaushik Majumdar   
14  Visakan Balakumar, Rafael P. Bernar, Luis C. B...   
15  G.G.Adamian, N.V.Antonenko, A.Diaz-Torres, W.S...   
16  BESIII Collaboration: M. Ablikim, M. N. Achaso...   
17  Sung Mook Lee, Dhong Yeon Cheong, Sang Chul Hy...   
18                                         S. Mignemi   
19            Sanjib Kumar Agarwalla, Pilar Hernandez   
20                          T-Y. Saito and I.R. Afnan   
21  S.J. Dong, T. Draper, I. Horvath, Nilmani Math...   
22  A.K. Karlis, P. K. Papachristou, F. K. Diakono...   
23  Lucas Tendick, Hermann Kampermann, Dagmar Bru{...   
24                                ATLAS Collaboration   

                                                title  \
0   Power-law cosmological solution derived from D...   
1   PyFstat: a Python package for continuous gravi...   
2   Holographic Superconductors with Power-Maxwell...   
3   Simultaneous assessment of energy, charge stat...   
4   Connectedness matters: Construction and exact ...   
5   A hybrid quantum system formed by trapping ato...   
6   Quantum state preparation by a shaped photon p...   
7             Local simultaneous state discrimination   
8   The 2019/20 Australian wildfires generated a p...   
9   Dark-State Optical Potential Barriers with Nan...   
10  Self-similarity in jet events following from p...   
11  Non-conservation of Carter in black hole space...   
12  Tamm's surface states and Bose-Einstein conden...   
13  Fourier Uniformity: An Useful Tool for Analyzi...   
14  Quantum superradiance on static black hole spa...   
15  Dynamical restriction for a growing neck due t...   
16  Measurement of the Cross Section for $e^{+}e^{...   
17  Festina-Lente Bound on Higgs Vacuum Structure ...   
18     Doubly Special Relativity and Finsler geometry   
19  Probing the Neutrino Mass Hierarchy with Super...   
20          How important is the three-nucleon force?   
21  Empirical Baye's Method and Test in Very Light...   
22  Hyperacceleration in a stochastic Fermi-Ulam m...   
23  Quantifying necessary quantum resources for no...   
24  Search for direct top squark pair production i...   

                                             abstract  \
0     By studying a tachyon field on the DGP brane...   
1     Gravitational waves in the sensitivity band ...   
2     With the Sturm-Liouville analytical and nume...   
3     We demonstrate simultaneous measurements of ...   
4     We describe a new method for the random samp...   
5     Near-field, radially symmetric optical poten...   
6     We propose a method to deterministically pre...   
7     Quantum state discrimination is one of the m...   
8     The Australian bushfires around the turn of ...   
9     Optical potentials have been a versatile too...   
10    Using a Tsallis nonextensive approach, we si...   
11    Freely falling point particles in the vicini...   
12    We calculate and discuss the effects on the ...   
13    If two signals are phase synchronous then th...   
14    We study the quantum analogue of the classic...   
15    Mass parameters for collective variables of ...   
16    Based on electron-positron collision data co...   
17    The recently suggested Festina-Lente (FL) bo... 

--- Kh√°m ph√° dictionary 'processed_data' ---
S·ªë l∆∞·ª£ng c·∫∑p key-value trong dictionary: 5

--- Th√¥ng tin chi ti·∫øt v·ªÅ t·ª´ng tr∆∞·ªùng trong dictionary ---
Key: abstract_embeddings
  - Ki·ªÉu d·ªØ li·ªáu: <class 'numpy.ndarray'>
  - K√≠ch th∆∞·ªõc (shape): (60000, 384)
--------------------
Key: parent_label_embeddings_dict
  - Ki·ªÉu d·ªØ li·ªáu: <class 'dict'>
  - S·ªë l∆∞·ª£ng ph·∫ßn t·ª≠ (len): 7
--------------------
Key: original_abstracts
  - Ki·ªÉu d·ªØ li·ªáu: <class 'list'>
  - S·ªë l∆∞·ª£ng ph·∫ßn t·ª≠ (len): 60000
--------------------
Key: original_parent_labels
  - Ki·ªÉu d·ªØ li·ªáu: <class 'list'>
  - S·ªë l∆∞·ª£ng ph·∫ßn t·ª≠ (len): 60000
--------------------
Key: original_children_labels
  - Ki·ªÉu d·ªØ li·ªáu: <class 'list'>
  - S·ªë l∆∞·ª£ng ph·∫ßn t·ª≠ (len): 60000
--------------------


```python
import pandas as pd
import ast
import json

# ===== C·∫•u h√¨nh =====
data_path = "arxiv_perfectly_balanced.csv"  # ƒë·ªïi n·∫øu c·∫ßn
out_path  = "dropped_col_df.csv"
cols = ["authors", "title", "abstract", "categories", "parent_labels", "child_labels"]

# ===== ƒê·ªçc file ch·ªâ l·∫•y c·ªôt c·∫ßn =====
df = pd.read_csv(data_path, usecols=cols)

# ===== Chu·∫©n ho√° 2 c·ªôt list (n·∫øu ƒëang l∆∞u d·∫°ng chu·ªói list trong CSV) =====
for col in ["parent_labels", "child_labels"]:
    df[col] = df[col].apply(
        lambda x: x if isinstance(x, list)
        else ([] if pd.isna(x) else ast.literal_eval(str(x)))
    )

# ===== T·∫°o c·ªôt json_categories: v·ªõi m·ªói cha, qu√©t to√†n b·ªô con ƒë·ªÉ l·∫•y con c√≥ ti·ªÅn t·ªë ƒë√∫ng =====
df["json_categories"] = df.apply(
    lambda r: {
        p: [c for c in (r["child_labels"] or [])
             if isinstance(c, str) and (c == p or c.startswith(p + ".") or c.startswith(p + "-"))]
        for p in (r["parent_labels"] or [])
    },
    axis=1
)

# Tu·ª≥ ch·ªçn: n·∫øu mu·ªën l∆∞u ra CSV ·ªü d·∫°ng chu·ªói JSON cho c·ªôt json_categories
df["json_categories"] = df["json_categories"].apply(lambda d: json.dumps(d, ensure_ascii=False))

# ===== L∆∞u k·∫øt qu·∫£ =====
df_processed=df.drop(columns=["categories", "parent_labels", "child_labels"])
df_processed.to_csv(out_path, index=False)  # b·ªè tham s·ªë file_name kh·ªèi ƒëo·∫°n l·ªánh to_csv
```

In [95]:
import pandas as pd
import ast
import json

# ===== C·∫•u h√¨nh =====
data_path = "/content/drive/MyDrive/AIO/top 30 main categories.csv"  # ƒê∆∞·ªùng d·∫´n file tr√™n Google Drive
out_path  = "processed_arxiv_data.csv" # T√™n file output (s·∫Ω l∆∞u trong th∆∞ m·ª•c hi·ªán t·∫°i c·ªßa Colab)
# ƒêi·ªÅu ch·ªânh c·ªôt theo y√™u c·∫ßu: categories l√† con, main_categories l√† cha
cols = ["authors", "title", "abstract", "categories", "main_categories"]

# ===== ƒê·ªçc file ch·ªâ l·∫•y c·ªôt c·∫ßn =====
df = pd.read_csv(data_path, usecols=cols)

# # ƒê·ªïi t√™n c·ªôt theo y√™u c·∫ßu - B·ªè qua b∆∞·ªõc ƒë·ªïi t√™n c·ªôt 'categories'
df = df.rename(columns={
    'main_categories': 'parent_labels'
})

# ===== Chu·∫©n ho√° 2 c·ªôt list (n·∫øu ƒëang l∆∞u d·∫°ng chu·ªói list trong CSV) =====
# C·∫ßn ki·ªÉm tra ki·ªÉu d·ªØ li·ªáu tr∆∞·ªõc khi √°p d·ª•ng ast.literal_eval
def safe_literal_eval(data, col_name):
    if isinstance(data, str):
        try:
            return ast.literal_eval(data)
        except (ValueError, SyntaxError):
            # N·∫øu kh√¥ng ph·∫£i chu·ªói list h·ª£p l·ªá, th·ª≠ t√°ch b·∫±ng d·∫•u c√°ch cho nh√£n con ('categories')
            # Ch√∫ √Ω: ƒê√¢y c√≥ th·ªÉ c·∫ßn ƒëi·ªÅu ch·ªânh t√πy v√†o format d·ªØ li·ªáu g·ªëc kh√¥ng ph·∫£i list string
            return data.split() if col_name == 'categories' and isinstance(data, str) else []
    elif isinstance(data, list):
        return data # N·∫øu ƒë√£ l√† list, gi·ªØ nguy√™n
    else:
        return [] # X·ª≠ l√Ω c√°c ki·ªÉu d·ªØ li·ªáu kh√°c (v√≠ d·ª•: NaN)

# √Åp d·ª•ng h√†m chu·∫©n h√≥a cho c·∫£ hai c·ªôt, truy·ªÅn t√™n c·ªôt ƒë·ªÉ x·ª≠ l√Ω 'categories' kh√°c
df['parent_labels'] = df['parent_labels'].apply(lambda x: safe_literal_eval(x, 'parent_labels'))
df['categories'] = df['categories'].apply(lambda x: safe_literal_eval(x, 'categories'))


# ===== T·∫°o c·ªôt json_categories: v·ªõi m·ªói cha, qu√©t to√†n b·ªô con ƒë·ªÉ l·∫•y con c√≥ ti·ªÅn t·ªë ƒë√∫ng =====
# S·ª≠ d·ª•ng t√™n c·ªôt 'categories' (nh√£n con)
df["json_categories"] = df.apply(
    lambda r: {
        p: [c for c in (r["categories"] or [])
             if isinstance(c, str) and (c == p or c.startswith(p + ".") or c.startswith(p + "-"))]
        for p in (r["parent_labels"] or [])
    },
    axis=1
)

# Tu·ª≥ ch·ªçn: n·∫øu mu·ªën l∆∞u ra CSV ·ªü d·∫°ng chu·ªói JSON cho c·ªôt json_categories
df["json_categories"] = df["json_categories"].apply(lambda d: json.dumps(d, ensure_ascii=False))

# ===== L∆∞u k·∫øt qu·∫£ =====
# Gi·ªØ l·∫°i c√°c c·ªôt c·∫ßn thi·∫øt sau khi x·ª≠ l√Ω, s·ª≠ d·ª•ng 'categories' cho nh√£n con
df_processed = df[['authors', 'title', 'abstract', 'categories', 'json_categories']]
df_processed.to_csv(out_path, index=False)

print(f"ƒê√£ x·ª≠ l√Ω v√† l∆∞u file '{out_path}' th√†nh c√¥ng.")
print(df_processed.head()) # In v√†i d√≤ng ƒë·∫ßu c·ªßa df_processed ƒë·ªÉ ki·ªÉm tra

ƒê√£ x·ª≠ l√Ω v√† l∆∞u file 'processed_arxiv_data.csv' th√†nh c√¥ng.
                                             authors  \
0       Yongli Ping, Lixin Xu, Hongya Liu, Ying Shao   
1  David Keitel, Rodrigo Tenorio, Gregory Ashton,...   
2             Jiliang Jing, Qiyuan Pan, Songbai Chen   
3  R. Hole\v{n}\'ak, S. Lohmann, F. Sekula and D....   
4                Szabolcs Horv\'at and Carl D. Modes   

                                               title  \
0  Power-law cosmological solution derived from D...   
1  PyFstat: a Python package for continuous gravi...   
2  Holographic Superconductors with Power-Maxwell...   
3  Simultaneous assessment of energy, charge stat...   
4  Connectedness matters: Construction and exact ...   

                                            abstract  \
0    By studying a tachyon field on the DGP brane...   
1    Gravitational waves in the sensitivity band ...   
2    With the Sturm-Liouville analytical and nume...   
3    We demonstrate simultaneous 

In [9]:
df_processed.head(100)

authors  \
0        Yongli Ping, Lixin Xu, Hongya Liu, Ying Shao   
1   David Keitel, Rodrigo Tenorio, Gregory Ashton,...   
2              Jiliang Jing, Qiyuan Pan, Songbai Chen   
3   R. Hole\v{n}\'ak, S. Lohmann, F. Sekula and D....   
4                 Szabolcs Horv\'at and Carl D. Modes   
..                                                ...   
95                    Chian-Shu Chen and Chia-Min Lin   
96                       Fady Bishara and Zhuoni Qian   
97  M. Bruni, S. Matarrese, S. Mollerach, and S. S...   
98                                         Ilia Musco   
99  Henning Bahl, Thomas Biek\"otter, Sven Heineme...   

                                                title  \
0   Power-law cosmological solution derived from D...   
1   PyFstat: a Python package for continuous gravi...   
2   Holographic Superconductors with Power-Maxwell...   
3   Simultaneous assessment of energy, charge stat...   
4   Connectedness matters: Construction and exact ...   
..                                                ...   
95  Cosmon as the Modulon: Non-Gaussianity from Da...   
96  Complementary constraints on $Zb\bar{b}$ coupl...   
97  On Relativistic Perturbations of Second and Hi...   
98  Threshold for primordial black holes: Dependen...   
99  HiggsTools: BSM scalar phenomenology with new ...   

                                             abstract  \
0     By studying a tachyon field on the DGP brane...   
1     Gravitational waves in the sensitivity band ...   
2     With the Sturm-Liouville analytical and nume...   
3     We demonstrate simultaneous measurements of ...   
4     We describe a new method for the random samp...   
..                                                ...   
95    In this paper, we show that the idea of grow...   
96    We propose a new strategy to probe the $Z$ b...   
97    We present the results of a study of the gau...   
98    Primordial black holes may have formed in th...   
99    The codes HiggsBounds and HiggsSignals compa...   

                          categories  \
0                           [hep-th]   
1               [gr-qc, astro-ph.IM]   
2                    [hep-th, gr-qc]   
3                  [physics.ins-det]   
4   [physics.soc-ph, cs.DM, math.CO]   
..                               ...   
95     [hep-ph, astro-ph.CO, hep-th]   
96                  [hep-ph, hep-ex]   
97                 [gr-qc, astro-ph]   
98              [gr-qc, astro-ph.CO]   
99                          [hep-ph]   

                                      json_categories  
0                              {"hep-th": ["hep-th"]}  
1   {"gr-qc": ["gr-qc"], "astro-ph": ["astro-ph.IM"]}  
2          {"hep-th": ["hep-th"], "gr-qc": ["gr-qc"]}  
3                    {"physics": ["physics.ins-det"]}  
4                     {"physics": ["physics.soc-ph"]}  
..                                                ...  
95  {"hep-ph": ["hep-ph"], "astro-ph": ["astro-ph....  
96       {"hep-ph": ["hep-ph"], "hep-ex": ["hep-ex"]}  
97     {"gr-qc": ["gr-qc"], "astro-ph": ["astro-ph"]}  
98  {"gr-qc": ["gr-qc"], "astro-ph": ["astro-ph.CO"]}  
99                             {"hep-ph": ["hep-ph"]}  

[100 rows x 5 columns]

In [96]:
# Ch·ªçn ch·ªâ c·ªôt 'json_categories'
json_categories_df = df_processed[['json_categories']]

# ƒê·ªãnh nghƒ©a t√™n file output
output_json_path = "/content/drive/MyDrive/AIO/json_categories_only.csv"

# L∆∞u DataFrame m·ªõi v√†o file CSV
json_categories_df.to_csv(output_json_path, index=False)

print(f"ƒê√£ l∆∞u file '{output_json_path}' ch·ªâ v·ªõi c·ªôt 'json_categories'.")

ƒê√£ l∆∞u file '/content/drive/MyDrive/AIO/json_categories_only.csv' ch·ªâ v·ªõi c·ªôt 'json_categories'.


In [11]:
len(df_processed)

60000

# Th·ªëng k√™ nh√£n cha, nh√£n con t·ª´ json_categories_df

In [11]:
df_processed = pd.read_csv('/content/drive/MyDrive/AIO/json_categories_only.csv')

In [97]:
import json
import pandas as pd
from collections import Counter, defaultdict

def analyze_arxiv_categories_extended(json_categories_data):
    """
    Ph√¢n t√≠ch json_categories:
    Tr·∫£ v·ªÅ:
      - parent_count: Counter({parent: s·ªë_entry_ch·ª©a_parent})
      - parent_unique_subcats: dict({parent: set(nh√£n_con_unique)})
      - parent_child_counts: dict({parent: Counter({child: t·∫ßn_su·∫•t})})
      - total_entries: t·ªïng s·ªë entry h·ª£p l·ªá (parse JSON OK)
    """
    parent_count = Counter()
    parent_unique_subcats = defaultdict(set)
    parent_child_counts = defaultdict(Counter)
    total_entries = 0

    for line in json_categories_data:
        if not isinstance(line, (str, dict)) or (isinstance(line, str) and not line.strip()):
            continue

        try:
            categories = json.loads(line.strip()) if isinstance(line, str) else line
            if not isinstance(categories, dict):
                continue
            total_entries += 1

            for parent, subcats in categories.items():
                parent_count[parent] += 1
                # Chu·∫©n ho√° subcats v·ªÅ list
                if subcats is None:
                    continue
                if not isinstance(subcats, list):
                    # N·∫øu l√† string "['a','b']" th√¨ c·ªë parse
                    try:
                        parsed = json.loads(subcats)
                        subcats = parsed if isinstance(parsed, list) else []
                    except Exception:
                        subcats = []

                for child in subcats:
                    parent_unique_subcats[parent].add(child)
                    parent_child_counts[parent][child] += 1

        except json.JSONDecodeError:
            # B·ªè qua JSON h·ªèng
            continue

    return parent_count, parent_unique_subcats, parent_child_counts, total_entries


def display_results_extended(parent_count, parent_unique_subcats, parent_child_counts, total_entries, top_k_children=10):
    """
    Hi·ªÉn th·ªã:
      - T·ªïng quan
      - B·∫£ng nh√£n cha: s·ªë l·∫ßn xu·∫•t hi·ªán + s·ªë nh√£n con unique
      - Top-k nh√£n con theo t·ª´ng nh√£n cha
    """
    total_parent_occurrences = sum(parent_count.values())
    print("üìä T·ªîNG QUAN")
    print("="*50)
    print(f"T·ªïng s·ªë entries h·ª£p l·ªá: {total_entries}")
    print(f"S·ªë nh√£n cha duy nh·∫•t: {len(parent_count)}")
    print(f"T·ªïng l∆∞·ª£t xu·∫•t hi·ªán nh√£n cha: {total_parent_occurrences}\n")

    # B·∫£ng nh√£n cha
    rows = []
    for p, c in parent_count.items():
        rows.append({
            "nh√£n_cha": p,
            "s·ªë_l·∫ßn_xu·∫•t_hi·ªán": c,
            "s·ªë_nh√£n_con_unique": len(parent_unique_subcats.get(p, set()))
        })
    df_parents = pd.DataFrame(rows).sort_values("s·ªë_l·∫ßn_xu·∫•t_hi·ªán", ascending=False)
    print("üìã TH·ªêNG K√ä NH√ÉN CHA")
    print(df_parents.head(20).to_string(index=False))
    print()

    # Top-k nh√£n con theo t·ª´ng nh√£n cha
    print("üîé TOP nh√£n con theo t·ª´ng nh√£n cha")
    print("="*50)
    for p in df_parents["nh√£n_cha"].tolist():
        cnt = parent_child_counts.get(p, Counter())
        if not cnt:
            continue
        total_sub = sum(cnt.values())
        top_items = cnt.most_common(top_k_children)
        top_list = [f"{ch} ({n}, {n/total_sub*100:.1f}%)" for ch, n in top_items]
        print(f"- {p}: {'; '.join(top_list)}")
    print()

    # Th·ªëng k√™ t√≥m t·∫Øt
    print("üìà T√ìM T·∫ÆT")
    print("="*50)
    for i, row in enumerate(df_parents.head(5).itertuples(index=False), 1):
        pct = row.s·ªë_l·∫ßn_xu·∫•t_hi·ªán / total_parent_occurrences * 100 if total_parent_occurrences else 0
        print(f"  {i}. {row.nh√£n_cha}: {row.s·ªë_l·∫ßn_xu·∫•t_hi·ªán} l·∫ßn ({pct:.1f}%)")


def results_to_dataframes(parent_count, parent_unique_subcats, parent_child_counts):
    """
    Chuy·ªÉn k·∫øt qu·∫£ sang 2 DataFrame:
      - df_parents: 1 d√≤ng/nh√£n_cha
      - df_parent_child: 1 d√≤ng/(nh√£n_cha, nh√£n_con) v·ªõi t·∫ßn su·∫•t
    """
    df_parents = pd.DataFrame([
        {
            "nh√£n_cha": p,
            "s·ªë_l·∫ßn_xu·∫•t_hi·ªán": parent_count[p],
            "s·ªë_nh√£n_con_unique": len(parent_unique_subcats.get(p, set())),
            "danh_s√°ch_nh√£n_con_unique": ", ".join(sorted(parent_unique_subcats.get(p, set())))
        }
        for p in parent_count.keys()
    ]).sort_values("s·ªë_l·∫ßn_xu·∫•t_hi·ªán", ascending=False)

    rows = []
    for p, counter in parent_child_counts.items():
        for ch, n in counter.items():
            rows.append({"nh√£n_cha": p, "nh√£n_con": ch, "t·∫ßn_su·∫•t": n})
    df_parent_child = pd.DataFrame(rows).sort_values(["nh√£n_cha", "t·∫ßn_su·∫•t"], ascending=[True, False])

    return df_parents, df_parent_child


def load_json_categories_column(file_path, col="json_categories"):
    """ƒê·ªçc CSV v√† tr·∫£ v·ªÅ list c·ªôt json_categories (b·ªè NaN)."""
    df = pd.read_csv(file_path)
    if col not in df.columns:
        raise KeyError(f"Kh√¥ng t√¨m th·∫•y c·ªôt '{col}' trong file.")
    return df[col].dropna().tolist()


# ============================
# V√≠ d·ª• ch·∫°y (ƒëi·ªÅn l·∫°i file_path c·ªßa b·∫°n)
# ============================
if __name__ == "__main__":
    print("üöÄ B·∫ÆT ƒê·∫¶U PH√ÇN T√çCH D·ªÆ LI·ªÜU ARXIV")
    file_path = "/content/drive/MyDrive/AIO/json_categories_only.csv"  # ƒë·ªïi theo ƒë∆∞·ªùng d·∫´n c·ªßa b·∫°n
    data = load_json_categories_column(file_path)

    print("üîÑ ƒêang ph√¢n t√≠ch d·ªØ li·ªáu...")
    parent_count, parent_unique_subcats, parent_child_counts, total_entries = analyze_arxiv_categories_extended(data)

    print("‚úÖ Ho√†n th√†nh ph√¢n t√≠ch!\n")
    display_results_extended(parent_count, parent_unique_subcats, parent_child_counts, total_entries, top_k_children=None)

    # Xu·∫•t CSV n·∫øu c·∫ßn
    df_parents, df_parent_child = results_to_dataframes(parent_count, parent_unique_subcats, parent_child_counts)
    df_parents.to_csv("arxiv_parent_summary.csv", index=False, encoding="utf-8")
    df_parent_child.to_csv("arxiv_parent_child_counts.csv", index=False, encoding="utf-8")
    print("üíæ ƒê√£ l∆∞u: arxiv_parent_summary.csv & arxiv_parent_child_counts.csv")


üöÄ B·∫ÆT ƒê·∫¶U PH√ÇN T√çCH D·ªÆ LI·ªÜU ARXIV
üîÑ ƒêang ph√¢n t√≠ch d·ªØ li·ªáu...
‚úÖ Ho√†n th√†nh ph√¢n t√≠ch!

üìä T·ªîNG QUAN
T·ªïng s·ªë entries h·ª£p l·ªá: 60000
S·ªë nh√£n cha duy nh·∫•t: 20
T·ªïng l∆∞·ª£t xu·∫•t hi·ªán nh√£n cha: 82000

üìã TH·ªêNG K√ä NH√ÉN CHA
nh√£n_cha  s·ªë_l·∫ßn_xu·∫•t_hi·ªán  s·ªë_nh√£n_con_unique
  hep-th             10000                   1
  hep-ph             10000                   1
   gr-qc              8000                   1
astro-ph              6000                   7
cond-mat              6000                  10
quant-ph              6000                   1
 physics              4000                  22
 nucl-th              4000                   1
  hep-ex              4000                   1
    math              4000                  33
 hep-lat              2000                   1
   q-bio              2000                  10
    nlin              2000                   5
    econ              2000                   3
      c

```
üöÄ B·∫ÆT ƒê·∫¶U PH√ÇN T√çCH D·ªÆ LI·ªÜU ARXIV
üîÑ ƒêang ph√¢n t√≠ch d·ªØ li·ªáu...
‚úÖ Ho√†n th√†nh ph√¢n t√≠ch!

üìä T·ªîNG QUAN
==================================================
T·ªïng s·ªë entries h·ª£p l·ªá: 60000
S·ªë nh√£n cha duy nh·∫•t: 20
T·ªïng l∆∞·ª£t xu·∫•t hi·ªán nh√£n cha: 82000

üìã TH·ªêNG K√ä NH√ÉN CHA
nh√£n_cha  s·ªë_l·∫ßn_xu·∫•t_hi·ªán  s·ªë_nh√£n_con_unique
  hep-th             10000                   1
  hep-ph             10000                   1
   gr-qc              8000                   1
astro-ph              6000                   7
cond-mat              6000                  10
quant-ph              6000                   1
 physics              4000                  22
 nucl-th              4000                   1
  hep-ex              4000                   1
    math              4000                  33
 hep-lat              2000                   1
   q-bio              2000                  10
    nlin              2000                   5
    econ              2000                   3
      cs              2000                  39
    eess              2000                   4
 math-ph              2000                   1
 nucl-ex              2000                   1
    stat              2000                   6
   q-fin              2000                   9

üîé TOP nh√£n con theo t·ª´ng nh√£n cha
==================================================
- hep-th: hep-th (10000, 100.0%)
- hep-ph: hep-ph (10000, 100.0%)
- gr-qc: gr-qc (8000, 100.0%)
- astro-ph: astro-ph.CO (2416, 35.9%); astro-ph.HE (1462, 21.7%); astro-ph (1330, 19.8%); astro-ph.GA (519, 7.7%); astro-ph.SR (512, 7.6%); astro-ph.IM (282, 4.2%); astro-ph.EP (208, 3.1%)
- cond-mat: cond-mat.stat-mech (1535, 21.2%); cond-mat.str-el (1523, 21.0%); cond-mat.mes-hall (1381, 19.1%); cond-mat.mtrl-sci (641, 8.9%); cond-mat.quant-gas (486, 6.7%); cond-mat.supr-con (486, 6.7%); cond-mat.other (384, 5.3%); cond-mat.dis-nn (290, 4.0%); cond-mat.soft (261, 3.6%); cond-mat (250, 3.5%)
- quant-ph: quant-ph (6000, 100.0%)
- physics: physics.optics (1351, 27.9%); physics.atom-ph (716, 14.8%); physics.chem-ph (357, 7.4%); physics.ins-det (279, 5.8%); physics.comp-ph (260, 5.4%); physics.flu-dyn (234, 4.8%); physics.app-ph (218, 4.5%); physics.hist-ph (215, 4.4%); physics.plasm-ph (167, 3.4%); physics.soc-ph (157, 3.2%); physics.bio-ph (132, 2.7%); physics.gen-ph (121, 2.5%); physics.class-ph (112, 2.3%); physics.data-an (98, 2.0%); physics.acc-ph (74, 1.5%); physics.med-ph (62, 1.3%); physics.ao-ph (56, 1.2%); physics.geo-ph (55, 1.1%); physics.ed-ph (54, 1.1%); physics.space-ph (47, 1.0%); physics.atm-clus (43, 0.9%); physics.pop-ph (33, 0.7%)
- nucl-th: nucl-th (4000, 100.0%)
- hep-ex: hep-ex (4000, 100.0%)
- math: math-ph (2070, 26.8%); math.MP (2070, 26.8%); math.AP (376, 4.9%); math.PR (296, 3.8%); math.CO (275, 3.6%); math.AG (229, 3.0%); math.DG (215, 2.8%); math.DS (188, 2.4%); math.NT (170, 2.2%); math.FA (156, 2.0%); math.OC (153, 2.0%); math.RT (143, 1.9%); math.NA (132, 1.7%); math.SP (121, 1.6%); math.CA (109, 1.4%); math.RA (94, 1.2%); math.GR (94, 1.2%); math.QA (93, 1.2%); math.GT (86, 1.1%); math.OA (84, 1.1%); math.CV (83, 1.1%); math.SG (67, 0.9%); math.ST (64, 0.8%); math.LO (63, 0.8%); math.AT (61, 0.8%); math.AC (55, 0.7%); math.MG (53, 0.7%); math.CT (33, 0.4%); math.GM (28, 0.4%); math.KT (24, 0.3%); math.GN (15, 0.2%); math.HO (12, 0.2%); math.IT (11, 0.1%)
- hep-lat: hep-lat (2000, 100.0%)
- q-bio: q-bio.PE (570, 23.6%); q-bio.QM (445, 18.4%); q-bio.NC (422, 17.5%); q-bio.BM (241, 10.0%); q-bio.MN (199, 8.2%); q-bio.GN (167, 6.9%); q-bio.TO (109, 4.5%); q-bio.CB (106, 4.4%); q-bio.SC (81, 3.4%); q-bio.OT (75, 3.1%)
- nlin: nlin.CD (760, 34.1%); nlin.SI (576, 25.8%); nlin.PS (510, 22.8%); nlin.AO (317, 14.2%); nlin.CG (69, 3.1%)
- econ: econ.GN (862, 41.6%); econ.EM (719, 34.7%); econ.TH (492, 23.7%)
- cs: cs.LG (551, 18.6%); cs.CV (400, 13.5%); cs.AI (302, 10.2%); cs.CL (222, 7.5%); cs.IT (173, 5.8%); cs.CR (125, 4.2%); cs.RO (97, 3.3%); cs.DS (91, 3.1%); cs.NI (78, 2.6%); cs.DC (77, 2.6%); cs.IR (67, 2.3%); cs.LO (64, 2.2%); cs.CY (59, 2.0%); cs.SI (59, 2.0%); cs.SE (54, 1.8%); cs.NE (51, 1.7%); cs.HC (50, 1.7%); cs.DM (49, 1.7%); cs.SY (44, 1.5%); cs.GT (36, 1.2%); cs.SD (31, 1.0%); cs.DB (30, 1.0%); cs.CC (29, 1.0%); cs.PL (25, 0.8%); cs.CG (23, 0.8%); cs.DL (22, 0.7%); cs.FL (20, 0.7%); cs.CE (20, 0.7%); cs.AR (17, 0.6%); cs.MA (16, 0.5%); cs.NA (14, 0.5%); cs.SC (11, 0.4%); cs.GR (11, 0.4%); cs.PF (11, 0.4%); cs.MM (9, 0.3%); cs.ET (9, 0.3%); cs.OH (8, 0.3%); cs.MS (7, 0.2%); cs.OS (3, 0.1%)
- eess: eess.SP (733, 34.8%); eess.IV (586, 27.8%); eess.SY (522, 24.8%); eess.AS (266, 12.6%)
- math-ph: math-ph (2000, 100.0%)
- nucl-ex: nucl-ex (2000, 100.0%)
- stat: stat.ME (870, 33.2%); stat.ML (828, 31.6%); stat.AP (529, 20.2%); stat.CO (235, 9.0%); stat.TH (112, 4.3%); stat.OT (43, 1.6%)
- q-fin: q-fin.ST (477, 17.7%); q-fin.MF (359, 13.4%); q-fin.RM (321, 11.9%); q-fin.GN (317, 11.8%); q-fin.CP (314, 11.7%); q-fin.PR (305, 11.3%); q-fin.PM (264, 9.8%); q-fin.TR (218, 8.1%); q-fin.EC (114, 4.2%)

üìà T√ìM T·∫ÆT
==================================================
  1. hep-th: 10000 l·∫ßn (12.2%)
  2. hep-ph: 10000 l·∫ßn (12.2%)
  3. gr-qc: 8000 l·∫ßn (9.8%)
  4. astro-ph: 6000 l·∫ßn (7.3%)
  5. cond-mat: 6000 l·∫ßn (7.3%)
üíæ ƒê√£ l∆∞u: arxiv_parent_summary.csv & arxiv_parent_child_counts.csv
```

### Ch·ªâ gi·ªØ l·∫°i c√°c nh√£n con quan tr·ªçng:
t·ª´ json_categories_df
gi·ªØ l·∫°i 50 nh√£n x·∫øp h·∫°ng cao nh·∫•t, v·ªõi m·ªói nh√£n l·∫•y 300 d√≤ng data

```
gi·ªù c·∫ßn short c√°c nh√£n con t·ª´ tr√™n xu·ªëng d∆∞·ªõi
l·∫•y 50 nh√£n con c√≥ s·ªë l·∫ßn xu·∫•t hi·ªán cao nh·∫•t

t·ª´ data g·ªëc, t·∫°o df m·ªõi ch·ªâ gi·ªØ l·∫°i 50 nh√£n con cao nh·∫•t n√†y, s·ªë l·∫ßn xu·∫•t hi·ªán c·ªßa m·ªói nh√£n con l√† kho·∫£ng 300 d√≤ng.
b·∫±ng c√°ch;
t·ª´ nh√£n cao nh·∫•t l·∫•y 300 d√≤ng xu·∫•t hi·ªán nh√£n con n√†y
ti·∫øp t·ª•c: v·ªõi nh√£n con ti·∫øp theo, ƒë·∫øm trong data ƒë√£ l·∫•y xem s·ªë l·∫ßn xu·∫•t hi·ªán c·ªßa nh√£n con th·ª© 2 n√†y l√† bao nhi√™u, thi·∫øu bao nhi√™u th√¨ l·∫•y b√π th√™m c√°c d√≤ng data
C·ª© v·∫≠y ti·∫øp t·ª•c
```

```

Ok, m√¨nh vi·∫øt s·∫µn ƒëo·∫°n code ‚Äúch·∫°y ƒë∆∞·ª£c ngay‚Äù theo ƒë√∫ng y√™u c·∫ßu:

L·∫•y top 50 nh√£n con ph·ªï bi·∫øn nh·∫•t t·ª´ d·ªØ li·ªáu g·ªëc (df_processed['categories']).

T·∫°o DataFrame m·ªõi g·ªìm t·ªëi ƒëa 300 d√≤ng cho m·ªói nh√£n con, ch·ªçn theo th·ª© t·ª± t·ª´ nh√£n con nhi·ªÅu ‚Üí √≠t.

Khi x√©t nh√£n con ti·∫øp theo, ƒë·∫øm s·ªë l·∫ßn nh√£n ƒë√≥ ƒë√£ xu·∫•t hi·ªán trong t·∫≠p ƒë√£ ch·ªçn (do b·ªã ‚ÄúƒÉn k√©‚Äù t·ª´ c√°c nh√£n tr∆∞·ªõc), v√† ch·ªâ l·∫•y b√π ph·∫ßn thi·∫øu t·ª´ c√°c d√≤ng ch∆∞a ƒë∆∞·ª£c l·∫•y.

Y√™u c·∫ßu d·ªØ li·ªáu g·ªëc: df_processed c√≥ c·ªôt categories l√† list nh√£n con (n·∫øu l√† chu·ªói d·∫°ng list c≈©ng ƒë∆∞·ª£c, code s·∫Ω chu·∫©n ho√°).
```

In [98]:
import pandas as pd
import ast
from collections import Counter, defaultdict

# --------------------------
# 1) Chu·∫©n ho√° c·ªôt categories v·ªÅ List[str]
# --------------------------
def normalize_categories_col(df, col="categories"):
    if col not in df.columns:
        raise KeyError(f"Kh√¥ng t√¨m th·∫•y c·ªôt '{col}' trong df.")
    def to_list(x):
        if isinstance(x, list):
            return x
        if pd.isna(x):
            return []
        if isinstance(x, str):
            # c·ªë g·∫Øng parse ki·ªÉu "['a','b']" ho·∫∑c '["a","b"]'
            try:
                v = ast.literal_eval(x)
                return v if isinstance(v, list) else []
            except Exception:
                # fallback: t√°ch theo d·∫•u ph·∫©y n·∫øu c·∫ßn
                return [s.strip() for s in x.split(",")] if "," in x else [x.strip()]
        return []
    out = df.copy()
    out[col] = out[col].apply(to_list)
    return out

# --------------------------
# 2) T·∫°o inverted index: child_label -> list ch·ªâ s·ªë d√≤ng
# --------------------------
def build_inverted_index(categories_series):
    inv = defaultdict(list)
    for i, cats in categories_series.items():
        for c in cats:
            inv[c].append(i)
    return inv

# --------------------------
# 3) L·∫•y top-K nh√£n con theo t·∫ßn su·∫•t xu·∫•t hi·ªán (ƒë·∫øm theo s·ªë d√≤ng c√≥ ch·ª©a nh√£n ƒë√≥)
# --------------------------
def top_k_child_labels(inverted_index, k=50):
    counts = {lbl: len(idxs) for lbl, idxs in inverted_index.items()}
    top = sorted(counts.items(), key=lambda x: x[1], reverse=True)[:k]
    return [lbl for lbl, _ in top], counts

# --------------------------
# 4) Ch·ªçn h√†ng theo chi·∫øn l∆∞·ª£c "ƒëi·ªÅn quota 300/nh√£n"
#     - Duy tr√¨ set ch·ªâ s·ªë ƒë√£ ch·ªçn
#     - V·ªõi m·ªói nh√£n: ƒë·∫øm ƒë√£ c√≥ bao nhi√™u trong set, b·ªï sung t·ª´ c√°c ·ª©ng vi√™n c√≤n l·∫°i
# --------------------------
def select_rows_by_label_quota(df, inverted_index, labels_in_order, quota_per_label=300):
    selected = set()                         # ch·ªâ s·ªë ƒë√£ ch·ªçn
    label_indices_sets = {l: set(inverted_index.get(l, [])) for l in labels_in_order}
    achieved_counts = {}                     # nh√£n -> s·ªë b·∫£n ghi th·ªèa ch·ª©a nh√£n trong t·∫≠p ƒë√£ ch·ªçn

    for lbl in labels_in_order:
        lbl_set = label_indices_sets[lbl]
        already = len(selected & lbl_set)    # s·ªë d√≤ng ch·ª©a nh√£n n√†y ƒë√£ ‚Äúc√≥ s·∫µn‚Äù trong t·∫≠p
        missing = max(0, quota_per_label - already)

        if missing > 0:
            # ·ª©ng vi√™n m·ªõi: c√°c d√≤ng ch·ª©a nh√£n n√†y nh∆∞ng ch∆∞a ƒë∆∞·ª£c ch·ªçn
            candidates = [i for i in inverted_index.get(lbl, []) if i not in selected]
            take = candidates[:missing]
            selected.update(take)

        # c·∫≠p nh·∫≠t l·∫°i achieved th·ª±c t·∫ø (sau khi th√™m)
        achieved_counts[lbl] = len(selected & lbl_set)

    # T·∫°o df_out theo th·ª© t·ª± xu·∫•t hi·ªán ban ƒë·∫ßu
    # (gi·ªØ nguy√™n th·ª© t·ª± g·ªëc ƒë·ªÉ d·ªÖ ki·ªÉm tra)
    selected_sorted = sorted(list(selected))
    df_out = df.loc[selected_sorted].copy()

    return df_out, achieved_counts

# --------------------------
# 5) Pipeline ch√≠nh
# --------------------------
def build_top50_quota_dataset(df_processed, categories_col="categories",
                              top_k=50, quota_per_label=300):
    # Chu·∫©n ho√°
    df_norm = normalize_categories_col(df_processed, col=categories_col)

    # Inverted index
    inv = build_inverted_index(df_norm[categories_col])

    # Top-K nh√£n con to√†n b·ªô
    top_labels, global_counts = top_k_child_labels(inv, k=top_k)
    print(f"Top {top_k} nh√£n con (theo s·ªë d√≤ng ch·ª©a nh√£n):")
    for i, lbl in enumerate(top_labels, 1):
        print(f"{i:>2}. {lbl}: {global_counts[lbl]} d√≤ng")

    # Ch·ªçn theo quota
    print("\nƒêang ch·ªçn d·ªØ li·ªáu theo quota m·ªói nh√£n =", quota_per_label)
    df_out, achieved = select_rows_by_label_quota(df_norm, inv, top_labels, quota_per_label=quota_per_label)

    # Th·ªëng k√™ ƒë·∫°t ƒë∆∞·ª£c
    print(f"\n‚úÖ Ho√†n t·∫•t. S·ªë d√≤ng trong t·∫≠p k·∫øt qu·∫£: {len(df_out)}")
    print("S·ªë d√≤ng ƒë·∫°t ƒë∆∞·ª£c cho t·ª´ng nh√£n (ƒë√£ t√≠nh c·∫£ 'ƒÉn k√©' t·ª´ nh√£n tr∆∞·ªõc):")
    for lbl in top_labels:
        got = achieved.get(lbl, 0)
        note = "" if got >= quota_per_label else f" (thi·∫øu {quota_per_label - got})"
        print(f"- {lbl}: {got}{note}")

    return df_out, top_labels, achieved

# ============================
# C√ÅCH D√ôNG:
# df_processed: DataFrame g·ªëc, c√≥ c·ªôt 'categories'
# ============================

# df_selected, top50_labels, per_label_counts = build_top50_quota_dataset(
#     df_processed,
#     categories_col="categories",
#     top_k=50,
#     quota_per_label=300
# )

# # (tu·ª≥ ch·ªçn) l∆∞u ra CSV
# df_selected.to_csv("top50_child_labels_quota300.csv", index=False, encoding="utf-8")


In [99]:
df_selected, top50_labels, per_label_counts = build_top50_quota_dataset(
    df_processed,
    categories_col="categories",
    top_k=50,
    quota_per_label=300
)

# (tu·ª≥ ch·ªçn) l∆∞u ra CSV
df_selected.to_csv("top50_child_labels_quota300.csv", index=False, encoding="utf-8")


Top 50 nh√£n con (theo s·ªë d√≤ng ch·ª©a nh√£n):
 1. hep-th: 11343 d√≤ng
 2. hep-ph: 10527 d√≤ng
 3. gr-qc: 8563 d√≤ng
 4. quant-ph: 6814 d√≤ng
 5. hep-ex: 4398 d√≤ng
 6. nucl-th: 4221 d√≤ng
 7. math-ph: 2792 d√≤ng
 8. math.MP: 2792 d√≤ng
 9. astro-ph.CO: 2425 d√≤ng
10. hep-lat: 2155 d√≤ng
11. nucl-ex: 2070 d√≤ng
12. cs.LG: 2004 d√≤ng
13. cond-mat.stat-mech: 1831 d√≤ng
14. physics.optics: 1652 d√≤ng
15. cond-mat.str-el: 1530 d√≤ng
16. astro-ph.HE: 1468 d√≤ng
17. cond-mat.mes-hall: 1453 d√≤ng
18. astro-ph: 1352 d√≤ng
19. stat.ML: 1266 d√≤ng
20. stat.ME: 1100 d√≤ng
21. q-fin.EC: 983 d√≤ng
22. nlin.CD: 926 d√≤ng
23. cs.CV: 899 d√≤ng
24. econ.GN: 887 d√≤ng
25. physics.atom-ph: 868 d√≤ng
26. eess.SP: 826 d√≤ng
27. stat.AP: 809 d√≤ng
28. econ.EM: 760 d√≤ng
29. nlin.SI: 759 d√≤ng
30. cond-mat.mtrl-sci: 732 d√≤ng
31. eess.IV: 644 d√≤ng
32. q-bio.PE: 628 d√≤ng
33. cs.SY: 624 d√≤ng
34. math.PR: 612 d√≤ng
35. nlin.PS: 584 d√≤ng
36. eess.SY: 560 d√≤ng
37. astro-ph.SR: 539 d√≤ng
38. physics.soc-ph:

# ƒë·∫øm s·ªë l·∫ßn xu·∫•t hi·ªán c·ªßa df_selected

In [100]:
import pandas as pd
import ast
from collections import Counter

def normalize_categories(x):
    """Chu·∫©n ho√° d·ªØ li·ªáu categories v·ªÅ list."""
    if isinstance(x, list):
        return x
    if pd.isna(x):
        return []
    if isinstance(x, str):
        try:
            v = ast.literal_eval(x)
            return v if isinstance(v, list) else [x.strip()]
        except Exception:
            return [x.strip()]
    return []

def count_label_frequencies(df: pd.DataFrame, col_name: str) -> pd.DataFrame:
    """
    ƒê·∫øm s·ªë l·∫ßn xu·∫•t hi·ªán c·ªßa t·∫•t c·∫£ nh√£n trong m·ªôt c·ªôt (multi-label).
    """
    all_labels = []
    for cats in df[col_name].apply(normalize_categories):
        all_labels.extend(cats)

    counts = Counter(all_labels)

    return (
        pd.DataFrame(counts.items(), columns=["nh√£n", "s·ªë_l·∫ßn_xu·∫•t_hi·ªán"])
          .sort_values("s·ªë_l·∫ßn_xu·∫•t_hi·ªán", ascending=False)
          .reset_index(drop=True)
    )

df_child_counts = count_label_frequencies(df_selected, "categories")
print(df_child_counts)

         nh√£n  s·ªë_l·∫ßn_xu·∫•t_hi·ªán
0    quant-ph              1457
1      hep-th               994
2      hep-ph               907
3       gr-qc               722
4       cs.LG               709
..        ...               ...
153     cs.PF                 1
154  chao-dyn                 1
155     cs.OH                 1
156   math.KT                 1
157   math.AC                 1

[158 rows x 2 columns]


In [101]:
df_child_counts

nh√£n  s·ªë_l·∫ßn_xu·∫•t_hi·ªán
0    quant-ph              1457
1      hep-th               994
2      hep-ph               907
3       gr-qc               722
4       cs.LG               709
..        ...               ...
153     cs.PF                 1
154  chao-dyn                 1
155     cs.OH                 1
156   math.KT                 1
157   math.AC                 1

[158 rows x 2 columns]

# Qua t·ª´ng d√≤ng data b·ªè nh√£n ph·ª• trong ƒë√≥  v√† ƒë·∫øm s·ªë l·∫ßn xu·∫•t hi·ªán sau khi x·ª≠ l√Ω

In [85]:
list50labels = [
    "hep-th",
    "hep-ph",
    "gr-qc",
    "quant-ph",
    "hep-ex",
    "nucl-th",
    "math-ph",
    "math.MP",
    "astro-ph.CO",
    "hep-lat",
    "nucl-ex",
    "cs.LG",
    "cond-mat.stat-mech",
    "physics.optics",
    "cond-mat.str-el",
    "astro-ph.HE",
    "cond-mat.mes-hall",
    "astro-ph",
    "stat.ML",
    "stat.ME",
    "q-fin.EC",
    "nlin.CD",
    "cs.CV",
    "econ.GN",
    "physics.atom-ph",
    "eess.SP",
    "stat.AP",
    "econ.EM",
    "nlin.SI",
    "cond-mat.mtrl-sci",
    "eess.IV",
    "q-bio.PE",
    "cs.SY",
    "math.PR",
    "nlin.PS",
    "eess.SY",
    "astro-ph.SR",
    "physics.soc-ph",
    "cs.AI",
    "cond-mat.quant-gas",
    "astro-ph.GA",
    "q-bio.QM",
    "cond-mat.supr-con",
    "econ.TH",
    "q-fin.ST",
    "q-bio.NC",
    "physics.chem-ph",
    "math.OC",
    "math.AP",
    "cond-mat.other"
]


In [88]:
import ast

# chu·∫©n ho√° categories th√†nh list
def normalize_categories(x):
    if isinstance(x, list):
        return x
    if pd.isna(x):
        return []
    if isinstance(x, str):
        try:
            v = ast.literal_eval(x)
            return v if isinstance(v, list) else [x.strip()]
        except Exception:
            return [s.strip() for s in x.split(",")] if "," in x else [x.strip()]
    return []

# gi·∫£ s·ª≠ b·∫°n c√≥ list 50 labels trong bi·∫øn list50labels
# v√≠ d·ª•: list50labels = ["hep-th", "hep-ph", "gr-qc", "quant-ph", ...]

# T·∫°o dataframe m·ªõi t·ª´ df_selected m√† kh√¥ng t√°c ƒë·ªông ƒë·∫øn b·∫£n g·ªëc
df_selected_top50 = df_selected.copy()
df_selected_top50["categories"] = df_selected_top50["categories"].apply(normalize_categories)

# l·ªçc l·∫°i categories theo list50labels
df_selected_top50["categories"] = df_selected_top50["categories"].apply(
    lambda cats: [c for c in cats if c in list50labels]
)

# lo·∫°i b·ªè c√°c d√≤ng tr·ªëng sau khi l·ªçc
df_selected_top50 = df_selected_top50[df_selected_top50["categories"].map(len) > 0].reset_index(drop=True)

print("‚úÖ Ho√†n t·∫•t. S·ªë d√≤ng c√≤n l·∫°i:", len(df_selected_top50))
print(df_selected_top50.head())


‚úÖ Ho√†n t·∫•t. S·ªë d√≤ng c√≤n l·∫°i: 11240
                                             authors  \
0       Yongli Ping, Lixin Xu, Hongya Liu, Ying Shao   
1  David Keitel, Rodrigo Tenorio, Gregory Ashton,...   
2             Jiliang Jing, Qiyuan Pan, Songbai Chen   
3                Szabolcs Horv\'at and Carl D. Modes   
4                         A. Hopper and P. F. Barker   

                                               title  \
0  Power-law cosmological solution derived from D...   
1  PyFstat: a Python package for continuous gravi...   
2  Holographic Superconductors with Power-Maxwell...   
3  Connectedness matters: Construction and exact ...   
4  A hybrid quantum system formed by trapping ato...   

                                            abstract  \
0    By studying a tachyon field on the DGP brane...   
1    Gravitational waves in the sensitivity band ...   
2    With the Sturm-Liouville analytical and nume...   
3    We describe a new method for the random samp...   


In [89]:
df_child_counts = count_label_frequencies(df_selected, "categories")
print(df_child_counts)

                  nh√£n  s·ªë_l·∫ßn_xu·∫•t_hi·ªán
0             quant-ph              1457
1               hep-th               994
2               hep-ph               907
3                gr-qc               722
4                cs.LG               709
5              math-ph               626
6              math.MP               626
7   cond-mat.stat-mech               447
8       physics.optics               419
9              stat.ML               410
10     cond-mat.str-el               405
11   cond-mat.mes-hall               390
12         astro-ph.CO               383
13               cs.CV               380
14             stat.ME               369
15         astro-ph.HE               355
16            q-fin.EC               354
17              hep-ex               351
18               cs.SY               343
19     physics.atom-ph               343
20             nucl-th               341
21             nlin.CD               340
22             eess.SP               336
23     

In [91]:
output_file = "/content/drive/MyDrive/AIO/df_selected_top50.csv"
df_selected_top50.to_csv(output_file, index=False, encoding="utf-8")

print(f"üíæ ƒê√£ l∆∞u DataFrame v√†o file: {output_file}")

üíæ ƒê√£ l∆∞u DataFrame v√†o file: /content/drive/MyDrive/AIO/df_selected_top50.csv


### ANN - T√≠nh to√°n cha con

In [111]:
df_selected_top50

authors  \
0           Yongli Ping, Lixin Xu, Hongya Liu, Ying Shao   
1      David Keitel, Rodrigo Tenorio, Gregory Ashton,...   
2                 Jiliang Jing, Qiyuan Pan, Songbai Chen   
3                    Szabolcs Horv\'at and Carl D. Modes   
4                             A. Hopper and P. F. Barker   
...                                                  ...   
11235  A. A. Banishev, J. Wagner, T. Emig, R. Zandi, ...   
11236  A. A. Demenev, A. A. Shchekin, A. V. Larionov,...   
11237     Stefan Rist, Patrizia Vignolo, Giovanna Morigi   
11238  Meg Mahat (1), Sergio Periera (2), Ian M. Wats...   
11239   Yaron Bromberg, Yoav Lahini and Yaron Silberberg   

                                                   title  \
0      Power-law cosmological solution derived from D...   
1      PyFstat: a Python package for continuous gravi...   
2      Holographic Superconductors with Power-Maxwell...   
3      Connectedness matters: Construction and exact ...   
4      A hybrid quantum system formed by trapping ato...   
...                                                  ...   
11235  Demonstration of Angle Dependent Casimir Force...   
11236  Kinetics of stimulated polariton scattering in...   
11237  Photonic spectrum of bichromatic optical lattices   
11238  Coherent Control of Acoustic Phonons in hybrid...   
11239       Bloch oscillations of Path-Entangled Photons   

                                                abstract  \
0        By studying a tachyon field on the DGP brane...   
1        Gravitational waves in the sensitivity band ...   
2        With the Sturm-Liouville analytical and nume...   
3        We describe a new method for the random samp...   
4        Near-field, radially symmetric optical poten...   
...                                                  ...   
11235    The normal Casimir force between a sinusoida...   
11236    We demonstrate for the first time the strong...   
11237    We study the photonic spectrum of a one-dime...   
11238    We demonstrate the modification of coherent ...   
11239    We show that when photons in N-particle path...   

                                        categories  \
0                                         [hep-th]   
1                                          [gr-qc]   
2                                  [hep-th, gr-qc]   
3                                 [physics.soc-ph]   
4      [quant-ph, physics.atom-ph, physics.optics]   
...                                            ...   
11235                   [quant-ph, cond-mat.other]   
11236                             [cond-mat.other]   
11237                   [quant-ph, cond-mat.other]   
11238          [cond-mat.mtrl-sci, cond-mat.other]   
11239                   [quant-ph, cond-mat.other]   

                                         json_categories  
0                                 {"hep-th": ["hep-th"]}  
1      {"gr-qc": ["gr-qc"], "astro-ph": ["astro-ph.IM"]}  
2             {"hep-th": ["hep-th"], "gr-qc": ["gr-qc"]}  
3                        {"physics": ["physics.soc-ph"]}  
4      {"quant-ph": ["quant-ph"], "physics": ["physic...  
...                                                  ...  
11235  {"quant-ph": ["quant-ph"], "cond-mat": ["cond-...  
11236                   {"cond-mat": ["cond-mat.other"]}  
11237  {"quant-ph": ["quant-ph"], "cond-mat": ["cond-...  
11238  {"cond-mat": ["cond-mat.mtrl-sci", "cond-mat.o...  
11239  {"quant-ph": ["quant-ph"], "cond-mat": ["cond-...  

[11240 rows x 5 columns]

In [105]:
!pip install pandas numpy scikit-learn sentence-transformers
!pip install faiss-gpu  # n·∫øu c√≥ GPU CUDA


ERROR: Could not find a version that satisfies the requirement faiss-gpu (from versions: none)
ERROR: No matching distribution found for faiss-gpu


In [107]:
!pip install faiss-cpu

   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 31.4/31.4 MB 58.4 MB/s eta 0:00:00


In [113]:
import pandas as pd
import numpy as np
import ast
import time

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import f1_score, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sentence_transformers import SentenceTransformer

# ----------------- 1. LOAD DATA -----------------
df = df_selected_top50.copy()

# Gh√©p 3 c·ªôt authors + title + abstract th√†nh text
df["text"] = (
    df["authors"].astype(str) + " " +
    df["title"].astype(str) + " " +
    df["abstract"].astype(str)
)

texts = df["text"].tolist()
labels = df["categories"].tolist()
print(f"‚úÖ Data: {len(df)} samples | text + categories ready")

# ----------------- 2. LABELS -----------------
mlb = MultiLabelBinarizer()
Y = mlb.fit_transform(labels)
print(f"‚úÖ {len(mlb.classes_)} unique labels. V√≠ d·ª•: {mlb.classes_[:10]}")

# ----------------- 3. EMBEDDINGS -----------------
print("üîÑ ƒêang t·∫°o embedding v·ªõi SentenceTransformer...")
start = time.time()
model = SentenceTransformer("all-MiniLM-L6-v2", device="cuda")
X = model.encode(texts, show_progress_bar=True, device="cuda")
X = np.array(X, dtype="float32")
print(f"‚úÖ Embedding xong: {X.shape} (th·ªùi gian {time.time()-start:.2f}s)")




‚úÖ Data: 11240 samples | text + categories ready
‚úÖ 50 unique labels. V√≠ d·ª•: ['astro-ph' 'astro-ph.CO' 'astro-ph.GA' 'astro-ph.HE' 'astro-ph.SR'
 'cond-mat.mes-hall' 'cond-mat.mtrl-sci' 'cond-mat.other'
 'cond-mat.quant-gas' 'cond-mat.stat-mech']
üîÑ ƒêang t·∫°o embedding v·ªõi SentenceTransformer...


Batches:   0%|          | 0/352 [00:00<?, ?it/s]

‚úÖ Embedding xong: (11240, 384) (th·ªùi gian 30.79s)
‚úÖ Split: train=8992, test=2248
üîÑ Hu·∫•n luy·ªán KNN...
‚úÖ Train xong (th·ªùi gian 0.06s)
üéØ ƒê√°nh gi√° KNN ‚Üí Accuracy=0.3394, F1-micro=0.6141, F1-macro=0.5676
üìä V√≠ d·ª• 5 sample ƒë·∫ßu ti√™n trong predict_df:
                                                 authors  \
4170   Yiju Ma, Kevin Swandi, Archie Chapman and Greg...   
10819      Ben Roig, Michael R. Blanton, Nicolas P. Ross   
318    Mustapha Azreg-A\"inou, Glauber T. Marques, Ma...   
3473   J. Billy (LCFIO), V. Josse (LCFIO), Z. Zuo (LC...   
9959   Thanh Nguyen, Vy Bui, Anh Thai, Van Lam, Chris...   

                                                   title  \
4170   Multi-Stage Compound Real Options Valuation in...   
10819  Unusual Broad-Line MgII Emitters Among Luminou...   
318           Phantom black holes and critical phenomena   
3473   Guided atom laser : a new tool for guided atom...   
9959   Virtual organelle self-coding for fluorescence...   



In [125]:
!pip install iterative-stratification

In [127]:

from sklearn.metrics import classification_report, jaccard_score
from iterstrat.ml_stratifiers import MultilabelStratifiedKFold, MultilabelStratifiedShuffleSplit

# ----------------- 4. TRAIN/TEST SPLIT (MULTILABEL STRATIFY) -----------------
msss = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_idx, test_idx in msss.split(X, Y):
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = Y[train_idx], Y[test_idx]
    idx_train, idx_test = df.index[train_idx], df.index[test_idx]

print(f"‚úÖ Split: train={X_train.shape[0]}, test={X_test.shape[0]}")

# ----------------- 5. TRAIN KNN -----------------
print("üîÑ Hu·∫•n luy·ªán KNN...")
knn = KNeighborsClassifier(n_neighbors=5, metric="cosine")
start = time.time()
knn.fit(X_train, y_train)
print(f"‚úÖ Train xong (th·ªùi gian {time.time()-start:.2f}s)")

# ----------------- 6. D·ª∞ ƒêO√ÅN -----------------
y_pred = knn.predict(X_test)
acc = accuracy_score(y_test, y_pred)
f1_micro = f1_score(y_test, y_pred, average="micro")
f1_macro = f1_score(y_test, y_pred, average="macro")
jaccard = jaccard_score(y_test, y_pred, average="samples")  # d√πng trung b√¨nh theo t·ª´ng sample

print(f"üéØ ƒê√°nh gi√° KNN ‚Üí Accuracy={acc:.4f}, F1-micro={f1_micro:.4f}, "
      f"F1-macro={f1_macro:.4f}, Jaccard={jaccard:.4f}")

# ----------------- 7. T·∫†O predict_df -----------------
true_labels = mlb.inverse_transform(y_test)
pred_labels = mlb.inverse_transform(y_pred)

predict_df = df.loc[idx_test].copy()
predict_df["true_labels"] = true_labels
predict_df["predicted_labels"] = pred_labels

print("üìä V√≠ d·ª• 5 sample ƒë·∫ßu ti√™n trong predict_df:")
print(predict_df[["authors", "title", "true_labels", "predicted_labels"]].head())

# ----------------- 8. SAVE K·∫æT QU·∫¢ -----------------
predict_df.to_csv("/content/drive/MyDrive/AIO/predict_results.csv", index=False, encoding="utf-8")
print("üíæ ƒê√£ l∆∞u k·∫øt qu·∫£ d·ª± ƒëo√°n v√†o file: /content/drive/MyDrive/AIO/predict_results.csv")

# ----------------- 9. REPORT CHI TI·∫æT -----------------
print("\nüìä Classification Report chi ti·∫øt cho t·ª´ng nh√£n:")
report = classification_report(y_test, y_pred, target_names=mlb.classes_, zero_division=0)
print(report)


‚úÖ Split: train=8991, test=2249
üîÑ Hu·∫•n luy·ªán KNN...
‚úÖ Train xong (th·ªùi gian 0.05s)
üéØ ƒê√°nh gi√° KNN ‚Üí Accuracy=0.3433, F1-micro=0.6147, F1-macro=0.5653, Jaccard=0.5227
üìä V√≠ d·ª• 5 sample ƒë·∫ßu ti√™n trong predict_df:
                                              authors  \
2              Jiliang Jing, Qiyuan Pan, Songbai Chen   
4                          A. Hopper and P. F. Barker   
6   Christian Majenz, Maris Ozols, Christian Schaf...   
9                  Alexander Grant, Eanna E. Flanagan   
11                                   Kaushik Majumdar   

                                                title  \
2   Holographic Superconductors with Power-Maxwell...   
4   A hybrid quantum system formed by trapping ato...   
6             Local simultaneous state discrimination   
9   Non-conservation of Carter in black hole space...   
11  Fourier Uniformity: An Useful Tool for Analyzi...   

                                    true_labels  \
2                      

R·ªìi üëç m√¨nh vi·∫øt l·∫°i m·ªôt b·∫£n **report g·ªçn ‚Äì r√µ ‚Äì d·ªÖ hi·ªÉu** cho k·∫øt qu·∫£ c·ªßa b·∫°n.

---

# üìë Report K·∫øt Qu·∫£ M√¥ H√¨nh KNN + ANN

## 1. √ù nghƒ©a c√°c metrics

### üîπ Accuracy

* Trong **multi-label classification**, m·ªôt sample ch·ªâ ƒë∆∞·ª£c coi l√† ƒë√∫ng khi **to√†n b·ªô t·∫≠p nh√£n** kh·ªõp v·ªõi ground truth.
* Do ƒë√≥ Accuracy th∆∞·ªùng th·∫•p h∆°n so v·ªõi F1.

### üîπ F1-micro

* T√≠nh **TP, FP, FN tr√™n to√†n b·ªô dataset** (g·ªôp h·∫øt c√°c nh√£n).
* **∆Øu ti√™n nh√£n ph·ªï bi·∫øn** (nhi·ªÅu d·ªØ li·ªáu).
* ƒêo m·ª©c ƒë·ªô m√¥ h√¨nh l√†m t·ªët tr√™n to√†n c·ª•c.

### üîπ F1-macro

* T√≠nh **F1 ri√™ng cho t·ª´ng nh√£n**, sau ƒë√≥ l·∫•y trung b√¨nh c·ªông.
* **T·∫•t c·∫£ nh√£n ƒë∆∞·ª£c coi tr·ªçng nh∆∞ nhau** (c√¢n b·∫±ng gi·ªØa nh√£n nhi·ªÅu v√† nh√£n √≠t).
* ƒêo m·ª©c ƒë·ªô m√¥ h√¨nh c√≥ **c√¥ng b·∫±ng v·ªõi c√°c nh√£n nh·ªè/l·∫ª** hay kh√¥ng.

---

## 2. Ph√¢n t√≠ch k·∫øt qu·∫£

* **Accuracy = 0.3394 (~34%)**
  ‚Üí Nghƒ©a l√† ch·ªâ 34% sample c√≥ to√†n b·ªô nh√£n d·ª± ƒëo√°n tr√πng kh·ªõp ho√†n to√†n v·ªõi nh√£n th·∫≠t. ƒê√¢y l√† con s·ªë **kh√° ·ªïn** trong b·ªëi c·∫£nh multi-label, v√¨ ch·ªâ c·∫ßn sai 1 nh√£n c≈©ng b·ªã t√≠nh l√† sai c·∫£ sample.

* **F1-micro = 0.6141 (~61%)**
  ‚Üí Khi x√©t to√†n b·ªô nh√£n (∆∞u ti√™n nh√£n ph·ªï bi·∫øn nh∆∞ *hep-th, hep-ph, gr-qc*), m√¥ h√¨nh d·ª± ƒëo√°n **kh√° t·ªët**.

* **F1-macro = 0.5676 (~57%)**
  ‚Üí Khi t√≠nh c√¥ng b·∫±ng cho t·ª´ng nh√£n (bao g·ªìm c·∫£ nh√£n √≠t d·ªØ li·ªáu nh∆∞ *econ.TH, math.OC, q-bio.*), m√¥ h√¨nh **y·∫øu h∆°n r√µ r·ªát**.
  ‚Üí ƒêi·ªÅu n√†y ch·ª©ng t·ªè:

  * Model **m·∫°nh v·ªõi nh√£n ph·ªï bi·∫øn**.
  * **Y·∫øu v·ªõi nh√£n hi·∫øm**, d·∫´n t·ªõi m·∫•t c√¢n b·∫±ng.


```
üéØ ƒê√°nh gi√° KNN ‚Üí Accuracy=0.3394, F1-micro=0.6141, F1-macro=0.5676, Jaccard=0.5195

üíæ ƒê√£ l∆∞u k·∫øt qu·∫£ d·ª± ƒëo√°n v√†o file: /content/drive/MyDrive/AIO/predict_results.csv

üìä Classification Report chi ti·∫øt cho t·ª´ng nh√£n:
                    precision    recall  f1-score   support

          astro-ph       0.47      0.12      0.19        59
       astro-ph.CO       0.57      0.41      0.48        73
       astro-ph.GA       0.53      0.47      0.50        58
       astro-ph.HE       0.69      0.50      0.58        68
       astro-ph.SR       0.75      0.44      0.56        54
 cond-mat.mes-hall       0.63      0.31      0.42        86
 cond-mat.mtrl-sci       0.92      0.56      0.69        61
    cond-mat.other       0.18      0.05      0.07        66
cond-mat.quant-gas       0.53      0.37      0.44        65
cond-mat.stat-mech       0.41      0.13      0.20       101
   cond-mat.str-el       0.49      0.45      0.46        74
 cond-mat.supr-con       0.73      0.67      0.70        52
             cs.AI       0.67      0.23      0.34        70
             cs.CV       0.78      0.79      0.79        73
             cs.LG       0.62      0.62      0.62       128
             cs.SY       0.80      0.61      0.69        66
           econ.EM       0.75      0.51      0.61        59
           econ.GN       0.52      0.30      0.38        53
           econ.TH       0.74      0.76      0.75        59
           eess.IV       0.80      0.82      0.81        60
           eess.SP       0.85      0.59      0.70        68
           eess.SY       0.77      0.60      0.67        60
             gr-qc       0.88      0.72      0.79       147
            hep-ex       0.83      0.62      0.71        77
           hep-lat       0.81      0.81      0.81        62
            hep-ph       0.82      0.73      0.77       184
            hep-th       0.79      0.63      0.70       215
           math-ph       0.69      0.46      0.55       135
           math.AP       0.79      0.46      0.58        65
           math.MP       0.69      0.46      0.55       135
           math.OC       0.48      0.30      0.37        50
           math.PR       0.89      0.48      0.63        66
           nlin.CD       0.85      0.52      0.64        64
           nlin.PS       0.67      0.49      0.57        57
           nlin.SI       0.67      0.66      0.67        65
           nucl-ex       0.85      0.84      0.85        62
           nucl-th       0.69      0.52      0.59        64
   physics.atom-ph       0.73      0.50      0.59        70
   physics.chem-ph       0.71      0.45      0.55        67
    physics.optics       0.61      0.43      0.50        82
    physics.soc-ph       0.56      0.30      0.39        67
          q-bio.NC       0.93      0.80      0.86        64
          q-bio.PE       0.81      0.81      0.81        57
          q-bio.QM       0.50      0.28      0.36        54
          q-fin.EC       0.59      0.36      0.45        61
          q-fin.ST       0.75      0.65      0.69        65
          quant-ph       0.86      0.83      0.84       320
           stat.AP       0.44      0.09      0.15        77
           stat.ME       0.51      0.32      0.39        69
           stat.ML       0.43      0.35      0.38        72

         micro avg       0.72      0.53      0.61      4086
         macro avg       0.68      0.50      0.57      4086
      weighted avg       0.70      0.53      0.59      4086
       samples avg       0.65      0.57      0.58      4086

```

```bash
                  nh√£n  s·ªë_l·∫ßn_xu·∫•t_hi·ªán
0             quant-ph              1457
1               hep-th               994
2               hep-ph               907
3                gr-qc               722
4                cs.LG               709
5              math-ph               626
6              math.MP               626
7   cond-mat.stat-mech               447
8       physics.optics               419
9              stat.ML               410
10     cond-mat.str-el               405
11   cond-mat.mes-hall               390
12         astro-ph.CO               383
13               cs.CV               380
14             stat.ME               369
15         astro-ph.HE               355
16            q-fin.EC               354
17              hep-ex               351
18               cs.SY               343
19     physics.atom-ph               343
20             nucl-th               341
21             nlin.CD               340
22             eess.SP               336
23             stat.AP               331
24   cond-mat.mtrl-sci               327
25             nlin.SI               325
26             econ.GN               321
27             hep-lat               316
28             nlin.PS               314
29             econ.EM               313
30            q-bio.PE               308
31            astro-ph               307
32             eess.IV               306
33             nucl-ex               306
34             math.PR               306
35             eess.SY               306
36      physics.soc-ph               305
37  cond-mat.quant-gas               303
38               cs.AI               302
39             econ.TH               302
40     physics.chem-ph               301
41            q-bio.NC               300
42            q-bio.QM               300
43   cond-mat.supr-con               300
44             math.OC               300
45            q-fin.ST               300
46      cond-mat.other               300
47         astro-ph.SR               300
48         astro-ph.GA               300
49             math.AP               300
```

# Model embedding m·∫°nh h∆°n